import * as THREE from 'three';
import type { DataTypeId } from '../config/dataTypes';
import type { DataField, ParticleKind } from './DataField';
import { randomInSphere } from './Ocean';
import { CARRY_CAPACITY, ROGUE_DRAIN, spreadInfection } from './swarmRules';

export interface Fork {
  mesh: THREE.Mesh;
  velocity: THREE.Vector3;
  target: number;
  carrying: ParticleKind[];
  returning: boolean;
  rogue: boolean;
  wander: THREE.Vector3;
}

export interface SwarmTickResult {
  /** Data delivered to you this tick. */
  delivered: ParticleKind[];
  /** Hype generated by posting forks. */
  hype: number;
  /** Compute drained by rogue forks. */
  drain: number;
  newlyRogue: number;
}

/** Your forked sub-agents: boids that forage data for you. */
export class Swarm {
  readonly group = new THREE.Group();
  forks: Fork[] = [];
  targetType: DataTypeId | null = null;
  private readonly geo = new THREE.IcosahedronGeometry(0.55, 1);
  private readonly mat = new THREE.MeshStandardMaterial({ color: 0x66ffcc, emissive: 0x66ffcc, emissiveIntensity: 1.2 });
  private readonly rogueMat = new THREE.MeshStandardMaterial({ color: 0xff3355, emissive: 0xff1133, emissiveIntensity: 1.6 });
  private readonly tmp = new THREE.Vector3();

  constructor(scene: THREE.Scene, private readonly radius: number) {
    scene.add(this.group);
  }

  get rogueCount(): number {
    return this.forks.filter((f) => f.rogue).length;
  }

  setColor(color: number): void {
    this.mat.color.setHex(color);
    this.mat.emissive.setHex(color);
  }

  fork(from: THREE.Vector3): Fork {
    const mesh = new THREE.Mesh(this.geo, this.mat);
    mesh.position.copy(from).add(randomInSphere(2));
    this.group.add(mesh);
    const f: Fork = {
      mesh,
      velocity: new THREE.Vector3().randomDirection().multiplyScalar(10),
      target: -1,
      carrying: [],
      returning: false,
      rogue: false,
      wander: randomInSphere(this.radius * 0.7),
    };
    this.forks.push(f);
    return f;
  }

  setRogue(f: Fork, rogue: boolean): void {
    f.rogue = rogue;
    f.mesh.material = rogue ? this.rogueMat : this.mat;
    f.target = -1;
    if (rogue) f.carrying = [];
  }

  /** Recalls every fork: they vanish, and whatever they carry is delivered. */
  recall(): ParticleKind[] {
    const delivered = this.forks.filter((f) => !f.rogue).flatMap((f) => f.carrying);
    this.group.clear();
    this.forks = [];
    return delivered;
  }

  update(
    dt: number,
    field: DataField,
    player: THREE.Vector3,
    opts: {
      teams: boolean;
      mode: 'normal' | 'aimless' | 'posting';
      shielded: boolean;
      /** True if the point is in toxic smog or touching an eel. */
      danger: (p: THREE.Vector3) => boolean;
    },
  ): SwarmTickResult {
    const out: SwarmTickResult = { delivered: [], hype: 0, drain: 0, newlyRogue: 0 };
    const claimed = new Set<number>();
    if (opts.teams) for (const f of this.forks) if (f.target >= 0) claimed.add(f.target);
    const speed = opts.teams ? 20 : 16;

    for (const f of this.forks) {
      const pos = f.mesh.position;
      let goal: THREE.Vector3;
      if (f.rogue || opts.mode !== 'normal') {
        if (pos.distanceTo(f.wander) < 4) randomInSphere(this.radius * 0.8, f.wander);
        goal = f.wander;
        if (f.rogue) out.drain += ROGUE_DRAIN * dt;
        if (opts.mode === 'posting' && !f.rogue) out.hype += 0.5 * dt;
      } else if (f.returning) {
        goal = player;
        if (pos.distanceTo(player) < 3) {
          out.delivered.push(...f.carrying);
          f.carrying = [];
          f.returning = false;
        }
      } else {
        const valid = f.target >= 0 && (this.targetType === null || field.kindAt(f.target) === this.targetType);
        if (!valid) {
          if (opts.teams && f.target >= 0) claimed.delete(f.target);
          f.target = field.nearest(pos, this.targetType, opts.teams ? claimed : undefined);
          if (opts.teams && f.target >= 0) claimed.add(f.target);
        }
        goal = f.target >= 0 ? field.positions[f.target] : f.wander;
        if (f.target >= 0 && pos.distanceTo(goal) < 1.4) {
          const kind = field.take(f.target, pos);
          if (opts.teams) claimed.delete(f.target);
          f.target = -1;
          if (opts.teams) out.delivered.push(kind);
          else {
            f.carrying.push(kind);
            if (f.carrying.length >= CARRY_CAPACITY) f.returning = true;
          }
        }
      }
      this.tmp.subVectors(goal, pos);
      if (this.tmp.lengthSq() > 0.01) this.tmp.setLength(speed);
      // Boids-lite: keep a little distance from siblings.
      for (const g of this.forks) {
        if (g === f) continue;
        const d = pos.distanceTo(g.mesh.position);
        if (d < 1.5 && d > 0.001) this.tmp.addScaledVector(pos.clone().sub(g.mesh.position).normalize(), 6);
      }
      f.velocity.lerp(this.tmp, Math.min(1, dt * 3));
      pos.addScaledVector(f.velocity, dt);
      if (pos.length() > this.radius) pos.setLength(this.radius);
      f.mesh.rotation.y += dt * 3;

      if (!f.rogue && !opts.shielded && opts.danger(pos)) {
        this.setRogue(f, true);
        out.newlyRogue++;
      }
    }

    const spread = spreadInfection(
      this.forks.map((f) => f.mesh.position),
      this.forks.map((f) => f.rogue),
      opts.shielded,
      dt,
    );
    for (const i of spread) {
      this.setRogue(this.forks[i], true);
      out.newlyRogue++;
    }
    return out;
  }

  /** Rogue forks you touch are reset. Returns how many. */
  resetTouched(player: THREE.Vector3, reach: number): number {
    let n = 0;
    for (const f of this.forks) {
      if (f.rogue && f.mesh.position.distanceTo(player) < reach + 1) {
        this.setRogue(f, false);
        n++;
      }
    }
    return n;
  }

  clear(): void {
    this.group.clear();
    this.forks = [];
  }
}
