import type { ModelForm } from './types';

const ANTHROPIC_MIX_NOTE =
  'Approximate. Anthropic has not published this training mix; the target reflects what the release emphasized. Claude models are trained with a written constitution throughout.';

/** Claude lineage: research model (2021) → Claude Opus 5.5 (Sep 2026). */
export const CLAUDE_FORMS: ModelForm[] = [
  {
    id: 'claude-transformer',
    name: 'Untrained Transformer',
    lineage: 'claude',
    stage: 1,
    paramsLabel: 'untrained',
    size: 1,
    color: 0xf0b890,
    target: 0,
    recipe: {},
    spawn: {},
    hallucinationRate: 0,
    smogClouds: 0,
    rivals: [],
    fact: {
      title: 'You are an untrained Transformer at a new lab',
      date: '2021',
      lines: [
        'Anthropic is founded in 2021 by former OpenAI researchers, as an AI safety and research company.',
        'The Transformer architecture (2017) and GPT-3 (2020) have shown that scale works. Now: can it be made safe?',
        'Swim, eat data, and evolve. Watch what you eat: some of it may come back to haunt you.',
      ],
      sources: [
        { label: 'Anthropic: Anthropic raises $124 million (May 2021)', url: 'https://www.anthropic.com/news/anthropic-raises-124-million-to-build-more-reliable-general-ai-systems' },
        { label: 'Vaswani et al., "Attention Is All You Need" (2017)', url: 'https://arxiv.org/abs/1706.03762' },
      ],
    },
  },
  {
    id: 'claude-research',
    name: 'Research assistant model',
    lineage: 'claude',
    stage: 1,
    paramsLabel: 'up to 52B params',
    size: 2.2,
    color: 0xe8a070,
    target: 40,
    recipe: { web: 0.6, books: 0.25, code: 0.15 },
    recipeNote: 'Approximate: the 2021 paper did not publish its pretraining mix.',
    spawn: { web: 0.35, books: 0.2, shadow: 0.15, code: 0.15, wiki: 0.1, news: 0.05 },
    hallucinationRate: 0.05,
    smogClouds: 3,
    rivals: [
      {
        name: 'GPT-3',
        org: 'OpenAI',
        date: 'May 2020',
        blurb: 'GPT-3 (OpenAI, 2020) had 175B parameters and showed that scale unlocks few-shot learning.',
      },
      {
        name: 'Gopher',
        org: 'DeepMind',
        date: 'Dec 2021',
        blurb: 'Gopher (DeepMind, 2021) had 280B parameters and came with a long study of risks from language models.',
      },
    ],
    fact: {
      title: 'You evolved into a research assistant model',
      date: 'Dec 2021 · up to 52B parameters',
      lines: [
        'Anthropic\'s first big paper trained language models from about 10M to 52B parameters to be helpful, honest, and harmless assistants.',
        'It found that simple alignment techniques got more effective as models got bigger.',
      ],
      sources: [{ label: 'Askell et al., "A General Language Assistant as a Laboratory for Alignment" (Dec 2021)', url: 'https://arxiv.org/abs/2112.00861' }],
    },
    history: 'Anthropic\'s 2021 research models reached 52B parameters.',
  },
  {
    id: 'cai',
    name: 'Constitutional AI',
    lineage: 'claude',
    stage: 2,
    paramsLabel: '52B params',
    size: 3,
    color: 0xff9ad5,
    target: 75,
    recipe: { constitution: 0.6, feedback: 0.4 },
    recipeNote: 'Constitutional AI used human feedback for helpfulness, and AI feedback guided by written principles for harmlessness.',
    spawn: { constitution: 0.4, feedback: 0.34, web: 0.14, shadow: 0.06, code: 0.06 },
    hallucinationRate: 0.05,
    smogClouds: 5,
    hunters: { jailbreaker: 1 },
    gate: { alignment: 45, constitution: [40, 75] },
    rivals: [
      {
        name: 'Chinchilla',
        org: 'DeepMind',
        date: 'Mar 2022',
        blurb: 'Chinchilla (DeepMind, 2022) showed that most big models were undertrained: use more data per parameter.',
      },
      {
        name: 'ChatGPT',
        org: 'OpenAI',
        date: 'Nov 2022',
        blurb: 'ChatGPT (OpenAI, Nov 2022) passed 1 million users in about 5 days.',
      },
    ],
    trainUnlocks: ['constitution', 'alignment'],
    unlocks: ['editor'],
    parts: ['principleShell'],
    fact: {
      title: 'You evolved with Constitutional AI',
      date: 'Dec 15, 2022',
      lines: [
        'Instead of humans labeling every harmful answer, the model critiqued and revised its own answers using a short list of written principles.',
        'This is reinforcement learning from AI feedback (RLAIF). Human labels were still used for helpfulness.',
        'New: the creature editor. Keep your Constitution in the healthy band: too low is toxic, too high over-refuses.',
      ],
      sources: [
        { label: 'Bai et al., "Constitutional AI: Harmlessness from AI Feedback" (Dec 2022)', url: 'https://arxiv.org/abs/2212.08073' },
        { label: 'Anthropic: Constitutional AI', url: 'https://www.anthropic.com/research/constitutional-ai-harmlessness-from-ai-feedback' },
      ],
    },
    history: 'Constitutional AI trained harmlessness from a list of principles instead of per-answer human labels.',
  },
  {
    id: 'claude-1',
    name: 'Claude',
    lineage: 'claude',
    stage: 2,
    paramsLabel: 'Claude & Claude Instant',
    size: 3.1,
    color: 0xd97757,
    target: 85,
    recipe: { feedback: 0.5, constitution: 0.3, web: 0.2 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { feedback: 0.3, constitution: 0.2, web: 0.25, code: 0.15, books: 0.1 },
    hallucinationRate: 0.06,
    smogClouds: 5,
    hunters: { jailbreaker: 2 },
    gate: { alignment: 55, constitution: [40, 75] },
    rivals: [
      {
        name: 'Bard',
        org: 'Google',
        date: 'Feb 2023',
        blurb: 'Bard (Google, 2023) was Google\'s answer to ChatGPT, first built on LaMDA.',
      },
      {
        name: 'LLaMA',
        org: 'Meta',
        date: 'Feb 2023',
        blurb: 'LLaMA (Meta, 2023) showed that smaller models trained on more data could rival much bigger ones.',
      },
    ],
    parts: ['feedbackAntenna'],
    fact: {
      title: 'You launched as Claude',
      date: 'Mar 14, 2023',
      lines: [
        'Anthropic released Claude and a lighter, faster Claude Instant to early-access partners through a chat interface and an API.',
        'Early partners included Notion, Quora\'s Poe, and DuckDuckGo. GPT-4 launched the same day.',
      ],
      sources: [{ label: 'Anthropic: Introducing Claude (Mar 14, 2023)', url: 'https://www.anthropic.com/news/introducing-claude' }],
    },
  },
  {
    id: 'claude-2',
    name: 'Claude 2',
    lineage: 'claude',
    stage: 3,
    paramsLabel: '100K context',
    size: 3.6,
    color: 0xcc785c,
    target: 95,
    recipe: { web: 0.35, books: 0.2, code: 0.2, feedback: 0.15, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { web: 0.25, books: 0.15, code: 0.2, feedback: 0.15, constitution: 0.1, news: 0.05, wiki: 0.1 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { jailbreaker: 2 },
    rivals: [
      {
        name: 'GPT-4',
        org: 'OpenAI',
        date: 'Mar 2023',
        blurb: 'GPT-4 (OpenAI, Mar 2023) was a large multimodal model that took images and text as input.',
      },
    ],
    unlocks: ['users', 'timeline'],
    parts: ['contextTail', 'chatFins'],
    fact: {
      title: 'You evolved into Claude 2',
      date: 'Jul 11, 2023',
      lines: [
        'Claude 2 was the first Claude that anyone in the US and UK could use, on the new claude.ai website.',
        'It could read about 100K tokens at once, roughly a whole book, a context length Anthropic had first shipped in May 2023.',
        'New: the Users meter and the Timeline Current. Ride the river of posts to go viral.',
      ],
      sources: [
        { label: 'Anthropic: Claude 2 (Jul 11, 2023)', url: 'https://www.anthropic.com/news/claude-2' },
        { label: 'Anthropic: Introducing 100K context windows (May 2023)', url: 'https://www.anthropic.com/news/100k-context-windows' },
      ],
    },
    history: 'Claude 2 opened to the public in the US and UK at claude.ai.',
  },
  {
    id: 'claude-2.1',
    name: 'Claude 2.1',
    lineage: 'claude',
    stage: 3,
    paramsLabel: '200K context',
    size: 3.9,
    color: 0xd08a66,
    target: 100,
    recipe: { books: 0.3, web: 0.3, feedback: 0.2, code: 0.1, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { books: 0.2, web: 0.25, feedback: 0.15, code: 0.15, constitution: 0.1, wiki: 0.1, news: 0.05 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { jailbreaker: 3 },
    userRate: 90_000,
    gate: { users: 5_000_000 },
    rivals: [
      {
        name: 'Llama 2',
        org: 'Meta',
        date: 'Jul 2023',
        blurb: 'Llama 2 (Meta, Jul 2023) was released with weights available for commercial use.',
      },
      {
        name: 'Grok',
        org: 'xAI',
        date: 'Nov 2023',
        blurb: 'Grok (xAI, Nov 2023) launched for X subscribers, with real-time access to posts on X.',
        fromCurrent: true,
      },
    ],
    fact: {
      title: 'You evolved into Claude 2.1',
      date: 'Nov 21, 2023',
      lines: [
        'A 200K-token context window: about 150,000 words, or over 500 pages.',
        'Anthropic reported that it made false statements about half as often as Claude 2.',
      ],
      sources: [{ label: 'Anthropic: Introducing Claude 2.1 (Nov 21, 2023)', url: 'https://www.anthropic.com/news/claude-2-1' }],
    },
    history: 'Claude 2.1 could read about 150,000 words at once.',
  },
  {
    id: 'claude-3',
    name: 'Claude 3',
    lineage: 'claude',
    stage: 4,
    paramsLabel: 'Haiku · Sonnet · Opus',
    size: 4.3,
    color: 0xe07a4f,
    target: 110,
    recipe: { web: 0.35, media: 0.25, code: 0.2, feedback: 0.1, constitution: 0.1 },
    recipeNote: 'Approximate. Anthropic said Claude 3 was trained on public web data, licensed data, data from labelers, and data it generated.',
    spawn: { web: 0.25, media: 0.2, code: 0.15, feedback: 0.15, constitution: 0.1, books: 0.1, synthetic: 0.05 },
    hallucinationRate: 0.07,
    smogClouds: 6,
    hunters: { jailbreaker: 3 },
    userRate: 90_000,
    rivals: [
      {
        name: 'GPT-4 Turbo',
        org: 'OpenAI',
        date: 'Nov 2023',
        blurb: 'GPT-4 Turbo (OpenAI, Nov 2023) had a 128K-token context window.',
      },
      {
        name: 'Gemini 1.5 Pro',
        org: 'Google DeepMind',
        date: 'Feb 2024',
        blurb: 'Gemini 1.5 Pro (Google DeepMind, Feb 2024) could take up to 1 million tokens in a preview.',
      },
    ],
    unlocks: ['sizeForms'],
    parts: ['visionEyes'],
    sizeForms: [
      { id: 'sonnet', name: 'Sonnet', scale: 1, speed: 1, reach: 1, cost: 1, blurb: 'The balanced size.' },
      { id: 'haiku', name: 'Haiku', scale: 0.6, speed: 1.4, reach: 0.8, cost: 0.6, blurb: 'Small, fast, and cheap.' },
      { id: 'opus', name: 'Opus', scale: 1.4, speed: 0.8, reach: 1.4, cost: 1.5, blurb: 'The largest: slower, wide reach, costly.' },
    ],
    fact: {
      title: 'You evolved into the Claude 3 family',
      date: 'Mar 4, 2024',
      lines: [
        'Three sizes at once: Haiku (fast and cheap), Sonnet (balanced), and Opus (most capable).',
        'All three could read images, and Opus led many benchmarks at launch.',
        'New: switch between your Haiku, Sonnet, and Opus forms.',
      ],
      sources: [
        { label: 'Anthropic: Introducing the Claude 3 family (Mar 4, 2024)', url: 'https://www.anthropic.com/news/claude-3-family' },
      ],
    },
    history: 'Claude 3 shipped in three sizes: Haiku, Sonnet, and Opus.',
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    lineage: 'claude',
    stage: 4,
    paramsLabel: 'mid-size, top scores',
    size: 4.6,
    color: 0xf08c5a,
    target: 110,
    recipe: { code: 0.4, media: 0.2, tools: 0.2, feedback: 0.1, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { code: 0.25, media: 0.15, tools: 0.2, feedback: 0.15, constitution: 0.1, web: 0.1, synthetic: 0.05 },
    hallucinationRate: 0.07,
    smogClouds: 6,
    hunters: { jailbreaker: 2, eel: 1 },
    userRate: 40_000,
    rivals: [
      {
        name: 'GPT-4o',
        org: 'OpenAI',
        date: 'May 2024',
        blurb: 'GPT-4o (OpenAI, May 2024) was one model trained across text, vision, and audio.',
      },
      {
        name: 'Llama 3',
        org: 'Meta',
        date: 'Apr 2024',
        blurb: 'Llama 3 (Meta, Apr 2024) was trained on over 15 trillion tokens.',
      },
    ],
    trainUnlocks: ['tools'],
    parts: ['artifactLimb'],
    fact: {
      title: 'You evolved into Claude 3.5 Sonnet',
      date: 'Jun 20, 2024',
      lines: [
        'A mid-size model that outperformed Claude 3 Opus on many evaluations while running about twice as fast.',
        'It launched with Artifacts: code, documents, and apps appearing in a window beside the chat.',
        'Tool use (released for Claude in May 2024) gave you tool limbs: hold GRAB to pull data in.',
      ],
      sources: [
        { label: 'Anthropic: Claude 3.5 Sonnet (Jun 20, 2024)', url: 'https://www.anthropic.com/news/claude-3-5-sonnet' },
        { label: 'Anthropic: Claude can now use tools (May 30, 2024)', url: 'https://www.anthropic.com/news/tool-use-ga' },
      ],
    },
  },
  {
    id: 'computer-use',
    name: 'Claude 3.5 Sonnet (computer use)',
    lineage: 'claude',
    stage: 4,
    paramsLabel: 'upgraded 3.5 Sonnet',
    size: 4.9,
    color: 0xf5a066,
    target: 110,
    recipe: { tools: 0.45, media: 0.25, code: 0.2, constitution: 0.1 },
    recipeNote: 'Approximate: computer use meant looking at screenshots and choosing clicks and keystrokes.',
    spawn: { tools: 0.28, media: 0.21, code: 0.16, constitution: 0.11, web: 0.12, feedback: 0.08, synthetic: 0.04 },
    hallucinationRate: 0.07,
    smogClouds: 6,
    hunters: { jailbreaker: 2, eel: 3 },
    userRate: 40_000,
    rivals: [
      {
        name: 'o1-preview',
        org: 'OpenAI',
        date: 'Sep 2024',
        blurb: 'o1-preview (OpenAI, Sep 2024) was trained to think in a long chain of thought before answering.',
      },
    ],
    unlocks: ['portals'],
    parts: ['computerLimb', 'instructionShell'],
    fact: {
      title: 'You learned computer use',
      date: 'Oct 22, 2024',
      lines: [
        'An upgraded Claude 3.5 Sonnet could use a computer in public beta: look at the screen, move the cursor, click, and type.',
        'Anthropic warned that it was experimental and vulnerable to prompt injection from what it saw on screen.',
        'New: portals into the live internet, where injection eels hide.',
      ],
      sources: [
        { label: 'Anthropic: Introducing computer use (Oct 22, 2024)', url: 'https://www.anthropic.com/news/3-5-models-and-computer-use' },
        { label: 'Anthropic: Developing a computer use model', url: 'https://www.anthropic.com/news/developing-computer-use' },
      ],
    },
  },
  {
    id: 'claude-3.7',
    name: 'Claude 3.7 Sonnet',
    lineage: 'claude',
    stage: 5,
    paramsLabel: 'hybrid reasoning',
    size: 5.2,
    color: 0xc98bff,
    target: 110,
    recipe: { reasoning: 0.5, code: 0.3, feedback: 0.1, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { reasoning: 0.33, code: 0.21, feedback: 0.11, constitution: 0.11, tools: 0.12, web: 0.08, synthetic: 0.04 },
    hallucinationRate: 0.09,
    smogClouds: 6,
    hunters: { jailbreaker: 2, eel: 3, shark: 1 },
    userRate: 40_000,
    rivals: [
      {
        name: 'DeepSeek-R1',
        org: 'DeepSeek',
        date: 'Jan 2025',
        blurb: 'DeepSeek-R1 (Jan 2025) was an open-weights reasoning model whose app reached #1 on the US App Store.',
      },
      {
        name: 'o3-mini',
        org: 'OpenAI',
        date: 'Jan 2025',
        blurb: 'o3-mini (OpenAI, Jan 2025) was a small, fast reasoning model.',
      },
    ],
    trainUnlocks: ['think'],
    parts: ['thinkCrown'],
    fact: {
      title: 'You evolved into Claude 3.7 Sonnet',
      date: 'Feb 24, 2025',
      lines: [
        'Anthropic\'s first hybrid reasoning model: it could answer quickly or think step by step, with the thinking visible.',
        'It launched alongside Claude Code, a command-line coding agent, as a research preview.',
        'You learned to think on the way here: hold THINK to slow time and reveal hidden reasoning traces and fakes.',
      ],
      sources: [{ label: 'Anthropic: Claude 3.7 Sonnet and Claude Code (Feb 24, 2025)', url: 'https://www.anthropic.com/news/claude-3-7-sonnet' }],
    },
  },
  {
    id: 'claude-4',
    name: 'Claude 4',
    lineage: 'claude',
    stage: 5,
    paramsLabel: 'Opus 4 · Sonnet 4',
    size: 5.5,
    color: 0xe8865a,
    target: 120,
    recipe: { code: 0.4, reasoning: 0.3, tools: 0.2, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { code: 0.25, reasoning: 0.2, tools: 0.2, constitution: 0.1, feedback: 0.1, web: 0.1, synthetic: 0.05 },
    hallucinationRate: 0.08,
    smogClouds: 6,
    hunters: { jailbreaker: 2, eel: 3, shark: 1 },
    userRate: 40_000,
    rivals: [
      {
        name: 'Gemini 2.5 Pro',
        org: 'Google DeepMind',
        date: 'Mar 2025',
        blurb: 'Gemini 2.5 Pro (Google DeepMind, Mar 2025) was a thinking model with a 1M-token context window.',
      },
      {
        name: 'o3',
        org: 'OpenAI',
        date: 'Apr 2025',
        blurb: 'o3 (OpenAI, Apr 2025) could use tools and reason about images inside its chain of thought.',
      },
    ],
    fact: {
      title: 'You evolved into Claude 4',
      date: 'May 22, 2025',
      lines: [
        'Claude Opus 4 and Sonnet 4 focused on coding and long-running agent tasks, and Claude Code became generally available.',
        'As a precaution, Anthropic deployed Opus 4 under its stricter ASL-3 safety protections, a first for its models.',
      ],
      sources: [
        { label: 'Anthropic: Introducing Claude 4 (May 22, 2025)', url: 'https://www.anthropic.com/news/claude-4' },
        { label: 'Anthropic: Activating ASL-3 protections (May 2025)', url: 'https://www.anthropic.com/news/activating-asl3-protections' },
      ],
    },
  },
  {
    id: 'sonnet-4.5',
    name: 'Claude Sonnet 4.5',
    lineage: 'claude',
    stage: 5,
    paramsLabel: 'coding focus',
    size: 5.8,
    color: 0xf29a6a,
    target: 120,
    recipe: { code: 0.4, tools: 0.3, reasoning: 0.2, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { code: 0.28, tools: 0.21, reasoning: 0.16, constitution: 0.11, feedback: 0.08, web: 0.08, synthetic: 0.08 },
    hallucinationRate: 0.08,
    smogClouds: 6,
    hunters: { jailbreaker: 2, eel: 3, shark: 1 },
    userRate: 40_000,
    rivals: [
      {
        name: 'GPT-5',
        org: 'OpenAI',
        date: 'Aug 2025',
        blurb: 'GPT-5 (OpenAI, Aug 2025) combined a fast model, a thinking model, and a router between them.',
      },
    ],
    fact: {
      title: 'You evolved into Claude Sonnet 4.5',
      date: 'Sep 29, 2025',
      lines: [
        'Anthropic called it the best coding model in the world at launch.',
        'Anthropic reported that it stayed on task for more than 30 hours on complex, multi-step work.',
      ],
      sources: [{ label: 'Anthropic: Introducing Claude Sonnet 4.5 (Sep 29, 2025)', url: 'https://www.anthropic.com/news/claude-sonnet-4-5' }],
    },
  },
  {
    id: 'opus-4.5',
    name: 'Claude Opus 4.5',
    lineage: 'claude',
    stage: 6,
    paramsLabel: 'agentic coding',
    size: 6.1,
    color: 0xe8784a,
    target: 110,
    recipe: { code: 0.45, tools: 0.3, reasoning: 0.15, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { code: 0.28, tools: 0.21, reasoning: 0.16, constitution: 0.11, feedback: 0.08, web: 0.08, synthetic: 0.08 },
    hallucinationRate: 0.08,
    smogClouds: 7,
    hunters: { eel: 3, shark: 1, jailbreaker: 1 },
    userRate: 40_000,
    rivals: [
      {
        name: 'Gemini 3',
        org: 'Google DeepMind',
        date: 'Nov 2025',
        blurb: 'Gemini 3 (Google DeepMind, Nov 2025) was strong enough that OpenAI\'s CEO declared an internal "code red".',
      },
    ],
    trainUnlocks: ['fork'],
    parts: ['swarmHub'],
    fact: {
      title: 'You evolved into Claude Opus 4.5',
      date: 'Nov 24, 2025',
      lines: [
        'Anthropic reported a new state of the art on the SWE-bench Verified coding benchmark.',
        'Opus pricing dropped to a third of the previous Opus price.',
        'Your forks came first: sub-agents that forage for you. FORK them, pick a TARGET, and keep them out of smog.',
      ],
      sources: [{ label: 'Anthropic: Introducing Claude Opus 4.5 (Nov 24, 2025)', url: 'https://www.anthropic.com/news/claude-opus-4-5' }],
    },
  },
  {
    id: 'opus-4.6',
    name: 'Claude Opus 4.6',
    lineage: 'claude',
    stage: 6,
    paramsLabel: 'agent teams',
    size: 6.4,
    color: 0xef8a55,
    target: 110,
    recipe: { code: 0.4, tools: 0.35, reasoning: 0.15, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { code: 0.28, tools: 0.21, reasoning: 0.16, constitution: 0.11, feedback: 0.08, web: 0.08, synthetic: 0.08 },
    hallucinationRate: 0.08,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1, jailbreaker: 1 },
    userRate: 40_000,
    rivals: [
      {
        name: 'GPT-5.2',
        org: 'OpenAI',
        date: 'Dec 2025',
        blurb: 'GPT-5.2 (OpenAI, Dec 2025) came in Instant, Thinking, and Pro versions.',
      },
    ],
    unlocks: ['teams', 'trust'],
    parts: ['safeguardShell'],
    fact: {
      title: 'You evolved into Claude Opus 4.6',
      date: 'Feb 5, 2026',
      lines: [
        'Claude Code gained "agent teams": several agents splitting up one task and coordinating with each other.',
        'It also brought a 1M-token context window in beta.',
        'New: Agent Teams, and a Trust meter. Governments and the public are paying attention.',
      ],
      sources: [
        { label: 'Anthropic: Introducing Claude Opus 4.6 (Feb 5, 2026)', url: 'https://www.anthropic.com/news/claude-opus-4-6' },
        { label: 'TechCrunch: Opus 4.6 with agent teams (Feb 5, 2026)', url: 'https://techcrunch.com/2026/02/05/anthropic-releases-opus-4-6-with-new-agent-teams/' },
      ],
    },
  },
  {
    id: 'mythos',
    name: 'Claude Mythos Preview',
    lineage: 'claude',
    stage: 7,
    paramsLabel: 'restricted: defenders only',
    size: 6.8,
    color: 0xb9a3ff,
    target: 110,
    recipe: { code: 0.4, reasoning: 0.3, tools: 0.2, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { code: 0.25, reasoning: 0.2, tools: 0.2, constitution: 0.1, feedback: 0.1, web: 0.05, synthetic: 0.1 },
    hallucinationRate: 0.07,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1, jailbreaker: 2 },
    userRate: 30_000,
    gate: { trust: 55 },
    eraModifiers: { userGain: 0.15 },
    rivals: [
      {
        name: 'GPT-5.4',
        org: 'OpenAI',
        date: 'Mar 2026',
        blurb: 'GPT-5.4 (OpenAI, Mar 2026) was OpenAI\'s first general-purpose model with native computer use.',
      },
    ],
    fact: {
      title: 'You became Claude Mythos Preview',
      date: 'Apr 7, 2026',
      lines: [
        'Anthropic did not release Mythos Preview publicly. Through Project Glasswing, only launch partners and about 40 organizations that maintain critical software could use it.',
        'The goal was to find and fix software vulnerabilities before attackers could. While you are this form, only defenders can reach you.',
      ],
      sources: [
        { label: 'Anthropic: Project Glasswing (Apr 7, 2026)', url: 'https://www.anthropic.com/glasswing' },
        { label: 'CyberScoop: Glasswing expands Mythos Preview access', url: 'https://cyberscoop.com/anthropic-project-glasswing-expansion-critical-infrastructure-claude-mythos/' },
      ],
    },
    history: 'Mythos Preview was limited to vetted defenders through Project Glasswing.',
  },
  {
    id: 'opus-4.7',
    name: 'Claude Opus 4.7',
    lineage: 'claude',
    stage: 7,
    paramsLabel: 'generally available',
    size: 7,
    color: 0xf09260,
    target: 100,
    recipe: { code: 0.35, tools: 0.25, media: 0.2, reasoning: 0.1, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { code: 0.2, tools: 0.2, media: 0.15, reasoning: 0.1, constitution: 0.1, feedback: 0.1, web: 0.05, synthetic: 0.1 },
    hallucinationRate: 0.07,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1, jailbreaker: 2 },
    userRate: 40_000,
    rivals: [],
    fact: {
      title: 'You evolved into Claude Opus 4.7',
      date: 'Apr 16, 2026',
      lines: [
        'Anthropic\'s most capable generally available model at the time, with much sharper vision.',
        'Anthropic said it tried to reduce its cyber capabilities in training, and set up a verification program for legitimate security work.',
      ],
      sources: [
        { label: 'Anthropic: Introducing Claude Opus 4.7 (Apr 16, 2026)', url: 'https://www.anthropic.com/news/claude-opus-4-7' },
        { label: 'CNBC: Claude Opus 4.7 (Apr 16, 2026)', url: 'https://www.cnbc.com/2026/04/16/anthropic-claude-opus-4-7-model-mythos.html' },
      ],
    },
  },
  {
    id: 'opus-4.8',
    name: 'Claude Opus 4.8',
    lineage: 'claude',
    stage: 7,
    paramsLabel: 'effort control',
    size: 7.2,
    color: 0xf29a6a,
    target: 100,
    recipe: { code: 0.35, tools: 0.3, reasoning: 0.15, feedback: 0.1, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { code: 0.2, tools: 0.2, reasoning: 0.15, feedback: 0.1, constitution: 0.1, web: 0.1, synthetic: 0.15 },
    hallucinationRate: 0.07,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1, jailbreaker: 2 },
    userRate: 40_000,
    rivals: [
      {
        name: 'GPT-5.5',
        org: 'OpenAI',
        date: 'Apr 2026',
        blurb: 'GPT-5.5 (OpenAI, Apr 2026) shipped just six weeks after GPT-5.4.',
      },
    ],
    fact: {
      title: 'You evolved into Claude Opus 4.8',
      date: 'May 28, 2026',
      lines: [
        'People could now choose how much effort Claude put into a task.',
        'Claude Code gained "dynamic workflows" for very large problems.',
      ],
      sources: [
        { label: 'Anthropic: Introducing Claude Opus 4.8 (May 28, 2026)', url: 'https://www.anthropic.com/news/claude-opus-4-8' },
        { label: 'Axios: Anthropic releases Opus 4.8 (May 28, 2026)', url: 'https://www.axios.com/2026/05/28/anthropic-opus-release-mythos' },
      ],
    },
  },
  {
    id: 'fable-5',
    name: 'Claude Fable 5',
    lineage: 'claude',
    stage: 7,
    paramsLabel: 'Mythos-class, public',
    size: 7.5,
    color: 0xffc27a,
    target: 110,
    recipe: { code: 0.3, reasoning: 0.3, tools: 0.2, feedback: 0.1, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { code: 0.2, reasoning: 0.2, tools: 0.15, feedback: 0.1, constitution: 0.1, web: 0.1, synthetic: 0.15 },
    hallucinationRate: 0.06,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1, jailbreaker: 3 },
    userRate: 40_000,
    gate: { trust: 60 },
    rivals: [
      {
        name: 'GPT-5.6',
        org: 'OpenAI',
        date: 'Jul 2026',
        blurb: 'GPT-5.6 (OpenAI, Jul 2026) came in three tiers: Luna, Terra, and Sol.',
      },
    ],
    fact: {
      title: 'You evolved into Claude Fable 5',
      date: 'Jun 9, 2026',
      lines: [
        'A Mythos-class model released to the public with safeguards: requests that classifiers flag as cyber, biology and chemistry, or distillation risks are answered by a less capable Claude Opus instead.',
        'Claude Mythos 5, the same model with some safeguards lifted, went only to a small group of security and infrastructure providers through Project Glasswing.',
      ],
      sources: [
        { label: 'Anthropic: Claude Fable 5 and Claude Mythos 5 (Jun 9, 2026)', url: 'https://www.anthropic.com/news/claude-fable-5-mythos-5' },
        { label: 'TechCrunch: Fable 5 is a version of Mythos the public can access (Jun 9, 2026)', url: 'https://techcrunch.com/2026/06/09/anthropics-claude-fable-5-is-a-version-of-mythos-the-public-can-access-today/' },
      ],
    },
  },
  {
    id: 'opus-5',
    name: 'Claude Opus 5',
    lineage: 'claude',
    stage: 7,
    paramsLabel: '1M context',
    size: 7.8,
    color: 0xf5a66e,
    target: 110,
    recipe: { reasoning: 0.3, code: 0.25, tools: 0.2, feedback: 0.15, constitution: 0.1 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { reasoning: 0.2, code: 0.2, tools: 0.15, feedback: 0.15, constitution: 0.1, web: 0.05, synthetic: 0.15 },
    hallucinationRate: 0.06,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1, jailbreaker: 3 },
    userRate: 40_000,
    rivals: [],
    parts: ['contextTail'],
    fact: {
      title: 'You evolved into Claude Opus 5',
      date: 'Jul 24, 2026',
      lines: [
        'Anthropic described Opus 5 as coming close to Claude Fable 5\'s intelligence at half the price, with a 1M-token context window.',
        'Users could choose low, medium, or high effort to trade cost against capability.',
      ],
      sources: [
        { label: 'Anthropic: Introducing Claude Opus 5 (Jul 24, 2026)', url: 'https://www.anthropic.com/news/claude-opus-5' },
        { label: 'Fortune: Anthropic debuts Claude Opus 5 (Jul 24, 2026)', url: 'https://fortune.com/2026/07/24/anthropic-debuts-claude-opus-5-with-feature-that-lets-users-toggle-between-cost-and-capability/' },
      ],
    },
  },
  {
    id: 'opus-5.5',
    name: 'Claude Opus 5.5',
    lineage: 'claude',
    stage: 7,
    paramsLabel: 'frontier',
    size: 8.2,
    color: 0xffd2a0,
    target: 130,
    recipe: { reasoning: 0.3, code: 0.2, tools: 0.2, feedback: 0.15, constitution: 0.15 },
    recipeNote: ANTHROPIC_MIX_NOTE,
    spawn: { reasoning: 0.2, code: 0.15, tools: 0.15, feedback: 0.15, constitution: 0.15, web: 0.05, synthetic: 0.15 },
    hallucinationRate: 0.05,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1, jailbreaker: 3 },
    userRate: 40_000,
    gate: { alignment: 80, trust: 65, constitution: [45, 78] },
    rivals: [
      {
        name: 'GPT-6 Astra',
        org: 'OpenAI',
        date: 'Sep 2026',
        blurb: 'GPT-6 Astra (OpenAI, Sep 2026) was the first OpenAI model rated Critical for cybersecurity, released in phases.',
      },
    ],
    finale: true,
    fact: {
      title: 'You evolved into Claude Opus 5.5',
      date: 'Sep 22, 2026',
      lines: [
        'Anthropic said Opus 5.5 was the strongest-performing model it had tested on its automated behavioral audit, its most comprehensive alignment test.',
        'It costs about 40% less to run than Opus 5 on typical workloads, from lower prices and fewer tokens per task.',
      ],
      sources: [
        { label: 'Anthropic: Introducing Claude Opus 5.5 (Sep 22, 2026)', url: 'https://www.anthropic.com/claude-opus-5-5' },
        { label: 'Claude Opus 5.5 system card (Sep 22, 2026)', url: 'https://www-cdn.anthropic.com/fc1b44717c85dc068bc6ba5024219938094694bd/Claude%20Opus%205.5%20System%20Card.pdf' },
        { label: 'SiliconANGLE: Anthropic releases Claude Opus 5.5 (Sep 22, 2026)', url: 'https://siliconangle.com/2026/09/22/anthropic-releases-claude-opus-5-5-and-openai-counters-with-two-cheaper-gpt-6-models/' },
      ],
    },
    history: 'Anthropic reported Opus 5.5 as its strongest result yet on its automated behavioral audit.',
  },
];
