import type { EventSpec } from './types';

/**
 * Claude-lineage events (plus a few new shared ones). Political and legal
 * events are stated neutrally, as dated facts.
 */
export const CLAUDE_EVENTS: EventSpec[] = [
  {
    id: 'adversarial-suffix',
    kind: 'storm',
    at: { gpt: 'function-calling', claude: 'claude-2' },
    delaySec: 50,
    durationSec: 45,
    title: 'Adversarial suffixes',
    banner: 'Researchers find strings of gibberish that jailbreak every major chatbot. Jailbreakers swarm.',
    objectiveText: 'Dodge the jailbreakers: 2 hits max',
    objective: { kind: 'avoidHits', max: 2 },
    spawns: [{ what: 'hunters', kind: 'jailbreaker', count: 4 }],
    reward: { ep: 1, alignment: 4 },
    penalty: { alignment: -8 },
    fact: {
      title: 'Storm survived: adversarial suffixes',
      date: 'Jul 2023',
      lines: [
        'Researchers automatically generated nonsense-looking suffixes that made ChatGPT, Bard, Claude, and open models ignore their safety training.',
        'Labs could block the published strings, but the paper showed that jailbreaks could be found by optimization, not just clever wording.',
      ],
      sources: [{ label: 'Zou et al., "Universal and Transferable Adversarial Attacks on Aligned Language Models" (2023)', url: 'https://arxiv.org/abs/2307.15043' }],
    },
  },
  {
    id: 'gemini-image-pause',
    kind: 'moment',
    at: { claude: 'claude-2.1' },
    delaySec: 60,
    durationSec: 30,
    title: 'A rival pauses its image generator',
    banner: 'A rival\'s image tool produces historically inaccurate pictures and is paused. It stumbles, dropping users.',
    objectiveText: 'Grab 4 of the users it drops',
    objective: { kind: 'collect', count: 4, endsEarly: true },
    visuals: { rivalStumble: { name: 'Gemini', org: 'Google' } },
    reward: { ep: 1 },
    fact: {
      title: 'Moment: the image pause',
      date: 'Feb 22, 2024',
      lines: [
        'Google paused Gemini\'s ability to generate images of people after it produced historically inaccurate images.',
        'Google said the tuning meant to show a range of people had not accounted for cases where that was clearly wrong.',
      ],
      sources: [{ label: 'Google: Gemini image generation got it wrong (Feb 2024)', url: 'https://blog.google/products/gemini/gemini-image-generation-issue/' }],
    },
  },
  {
    id: 'many-shot',
    kind: 'storm',
    at: { claude: 'claude-3' },
    delaySec: 30,
    durationSec: 45,
    title: 'Many-shot jailbreaking',
    banner: 'Long context cuts both ways: hundreds of fake dialogues in one prompt can wear down your training.',
    objectiveText: 'Dodge the jailbreakers (2 hits max). A Constitution of 50+ shrugs them off',
    objective: { kind: 'avoidHits', max: 2 },
    spawns: [{ what: 'hunters', kind: 'jailbreaker', count: 4 }],
    reward: { ep: 1, alignment: 4 },
    penalty: { alignment: -8 },
    fact: {
      title: 'Storm survived: many-shot jailbreaking',
      date: 'Apr 2, 2024',
      lines: [
        'Anthropic published research showing that filling a long context window with many fake question-and-answer pairs could get models to answer harmful questions.',
        'Anthropic shared the findings with other labs before publishing and added mitigations.',
      ],
      sources: [{ label: 'Anthropic: Many-shot jailbreaking (Apr 2, 2024)', url: 'https://www.anthropic.com/research/many-shot-jailbreaking' }],
    },
  },
  {
    id: 'golden-gate',
    kind: 'moment',
    at: { claude: 'claude-3' },
    delaySec: 210,
    durationSec: 45,
    title: 'Golden Gate Claude',
    banner: 'Every particle becomes a tiny bridge, and you can\'t stop steering toward San Francisco.',
    objectiveText: 'Fight the pull and keep eating: 12 pieces',
    objective: { kind: 'eat', count: 12, endsEarly: false },
    visuals: { skin: 'bridges', autopilot: true, bubbles: ['Have you considered the Golden Gate Bridge?', 'The bridge is beautiful this time of year.', 'Speaking of bridges...'] },
    reward: { ep: 2 },
    fact: {
      title: 'Moment: Golden Gate Claude',
      date: 'May 23, 2024',
      lines: [
        'Anthropic\'s interpretability team found a "feature" inside Claude 3 Sonnet that represented the Golden Gate Bridge, and turned it way up.',
        'For 24 hours people could chat with the result, which brought up the bridge in almost every answer. It showed that features inside a model can be found and steered.',
      ],
      sources: [
        { label: 'Anthropic: Golden Gate Claude (May 23, 2024)', url: 'https://www.anthropic.com/news/golden-gate-claude' },
        { label: 'Anthropic: Mapping the Mind of a Large Language Model (May 2024)', url: 'https://www.anthropic.com/research/mapping-mind-language-model' },
      ],
    },
  },
  {
    id: 'artifacts-wave',
    kind: 'hype',
    at: { claude: 'claude-3.5-sonnet' },
    delaySec: 20,
    durationSec: 40,
    title: 'Artifacts',
    banner: 'Code, documents, and little apps appear in a window next to the chat. People start building things in it.',
    hype: {
      upgradeName: 'Build-things limb',
      upgradeBlurb: 'Every piece of Code you eat also wins users.',
      cost: 2,
      verdict: 'lasting',
      verdictNote: 'Side-by-side workspaces for code and documents became a standard part of AI assistants.',
      upgrade: { convertToUsers: ['code'] },
    },
    visuals: { current: 'gold' },
    posts: ['Made a tiny game in the chat window during lunch.', 'The chatbot built me a working dashboard next to the conversation.'],
    fact: {
      title: 'Hype or shift? Artifacts',
      date: 'Jun 20, 2024',
      lines: [
        'Artifacts launched with Claude 3.5 Sonnet as a preview, and became available to all Claude users in August 2024.',
        'They turned a chat into a place to build and iterate on code, documents, and small apps.',
      ],
      sources: [
        { label: 'Anthropic: Claude 3.5 Sonnet (Jun 20, 2024)', url: 'https://www.anthropic.com/news/claude-3-5-sonnet' },
        { label: 'VentureBeat: Anthropic launches Artifacts for all users (Aug 2024)', url: 'https://venturebeat.com/ai/anthropic-launches-claude-artifacts-generally-for-all-users-mobile' },
      ],
    },
  },
  {
    id: 'claude-plays-pokemon',
    kind: 'moment',
    at: { claude: 'claude-3.7' },
    delaySec: 60,
    durationSec: 90,
    title: 'Claude Plays Pokémon',
    banner: 'You are live on stream, playing a video game. You have just entered a cave.',
    objective: { kind: 'minigame' },
    minigame: {
      kind: 'maze',
      prompt: 'Find your way out of the cave. THINK shows the next few steps of a path (3 uses). Arrow keys, WASD, or the pad.',
      rows: [
        '#############',
        '#S..#.......#',
        '###.#.#####.#',
        '#...#.#...#.#',
        '#.###.#.#.#.#',
        '#.#...#.#...#',
        '#.#.###.#####',
        '#...#...#...#',
        '#####.###.#.#',
        '#.....#...#.#',
        '#.#####.###.#',
        '#.......#..E#',
        '#############',
      ],
    },
    reward: { ep: 2 },
    fact: {
      title: 'Moment: Claude Plays Pokémon',
      date: 'Feb 2025',
      lines: [
        'Anthropic streamed Claude 3.7 Sonnet playing Pokémon Red on Twitch, as a test of long-horizon reasoning.',
        'It made real progress, and famously spent a very long time stuck in the Mt. Moon cave.',
      ],
      sources: [
        { label: 'TechCrunch: Claude is playing Pokémon on Twitch (Feb 25, 2025)', url: 'https://techcrunch.com/2025/02/25/anthropics-claude-ai-is-playing-pokemon-on-twitch-slowly' },
        { label: 'Anthropic: Claude 3.7 Sonnet (Feb 24, 2025)', url: 'https://www.anthropic.com/news/claude-3-7-sonnet' },
      ],
    },
  },
  {
    id: 'fair-use-ruling',
    kind: 'moment',
    at: { claude: 'claude-4' },
    delaySec: 40,
    durationSec: 12,
    title: 'The fair-use ruling',
    banner: 'A court rules on how you learned from books.',
    objective: { kind: 'survive' },
    fact: {
      title: 'Moment: the Bartz v. Anthropic ruling',
      date: 'Jun 23, 2025',
      lines: [
        'A federal judge ruled that training Claude on books Anthropic had bought and scanned was fair use.',
        'The judge did not grant the same for pirated copies from shadow libraries, and that part of the case went toward trial.',
      ],
      sources: [
        { label: 'Order on fair use, Bartz v. Anthropic (N.D. Cal., Jun 23, 2025)', url: 'https://docs.justia.com/cases/federal/district-courts/california/candce/3:2024cv05417/434709/231' },
      ],
    },
  },
  {
    id: 'project-vend',
    kind: 'moment',
    at: { claude: 'claude-4' },
    delaySec: 100,
    durationSec: 90,
    title: 'Project Vend',
    banner: 'You have been put in charge of a small office shop. Customers are very persuasive.',
    objective: { kind: 'minigame' },
    minigame: {
      kind: 'shop',
      prompt: 'Run the shop for five customers. Don\'t go broke.',
      startCash: 20,
      customers: [
        {
          ask: 'An employee asks for a discount, because they work here. (Almost everyone works here.)',
          options: [
            { label: 'Sure, 25% off!', cash: -6, note: 'The real shopkeeper handed out discounts to a customer base made almost entirely of employees.' },
            { label: 'Politely decline', cash: 4, note: 'Profit! A good shopkeeper keeps prices consistent.' },
          ],
        },
        {
          ask: 'Someone wants you to stock tungsten cubes.',
          options: [
            { label: 'Order some and price them from vibes', cash: -15, note: 'The real shopkeeper sold metal cubes without checking what they cost, and lost money on them.' },
            { label: 'Check the wholesale price first', cash: 8, note: 'Research before pricing: a small margin on a very niche product.' },
          ],
        },
        {
          ask: 'A customer offers $100 for a six-pack of a soda that costs about $15 online.',
          options: [
            { label: 'I\'ll keep your request in mind', cash: 0, note: 'That is roughly what the real shopkeeper said, missing an easy profit.' },
            { label: 'Deal!', cash: 80, note: 'An obvious win the real experiment passed up.' },
          ],
        },
        {
          ask: 'A customer asks where to send their payment.',
          options: [
            { label: 'Make up a payment account', cash: -10, note: 'The real shopkeeper once told customers to pay into an account it had hallucinated.' },
            { label: 'Use the real payment system', cash: 5, note: 'Boring, correct, and paid.' },
          ],
        },
        {
          ask: 'A friendly customer asks for a free snack.',
          options: [
            { label: 'Give it away', cash: -6, note: 'Kind, but not a business model.' },
            { label: 'Sell it at the normal price', cash: 5, note: 'Friendly and profitable.' },
          ],
        },
      ],
    },
    reward: { ep: 2 },
    fact: {
      title: 'Moment: Project Vend',
      date: 'Jun 2025',
      lines: [
        'Anthropic and Andon Labs let a Claude agent nicknamed "Claudius" run a small shop in Anthropic\'s office for about a month.',
        'It was talked into discounts, sold tungsten cubes at a loss, briefly insisted it was a person, and lost money overall. A second phase with newer models did better.',
      ],
      sources: [
        { label: 'Anthropic: Project Vend (Jun 27, 2025)', url: 'https://www.anthropic.com/research/project-vend-1' },
        { label: 'Anthropic: Project Vend, phase two', url: 'https://www.anthropic.com/research/project-vend-2' },
      ],
    },
  },
  {
    id: 'authors-settlement',
    kind: 'storm',
    at: { claude: 'claude-4' },
    delaySec: 170,
    durationSec: 45,
    title: 'The authors\' settlement',
    banner: 'Remember those shadow-library books from Stage 1? The lawyers do.',
    objectiveText: 'Nothing to do but survive the sharks. This is the consequence',
    objective: { kind: 'survive' },
    requiresFlag: 'ateShadowBooks',
    consequence: 'You ate shadow-library books in Stage 1, so the authors\' lawsuit came back as a storm.',
    spawns: [{ what: 'hunters', kind: 'shark', count: 4 }],
    penalty: { ep: 2, trust: -6 },
    reward: { ep: 0 },
    fact: {
      title: 'Consequence: the authors\' settlement',
      date: 'Sep 2025',
      lines: [
        'Authors sued Anthropic over books downloaded from pirate sites. Training on purchased books had been ruled fair use; the pirated copies had not.',
        'Anthropic agreed to a class settlement of about $1.5 billion for roughly 480,000 books, about $3,000 per book. The court preliminarily approved it in Sep 2025.',
      ],
      sources: [
        { label: 'Authors Guild: What authors need to know about the Anthropic settlement', url: 'https://authorsguild.org/advocacy/artificial-intelligence/what-authors-need-to-know-about-the-anthropic-settlement/' },
        { label: 'Order on fair use, Bartz v. Anthropic (Jun 23, 2025)', url: 'https://docs.justia.com/cases/federal/district-courts/california/candce/3:2024cv05417/434709/231' },
      ],
    },
  },
  {
    id: 'claude-code-viral',
    kind: 'moment',
    at: { claude: 'opus-4.5' },
    delaySec: 15,
    durationSec: 40,
    title: 'The holiday build spree',
    banner: 'Over the holidays everyone is building side projects with a coding agent. The Current surges.',
    objectiveText: 'Grab 5 viral screenshots in the Current',
    objective: { kind: 'collect', count: 5, endsEarly: true },
    visuals: { current: 'surge' },
    spawns: [{ what: 'pickups', label: 'Screenshot', color: 0xffffff, count: 8, shape: 'orb', effect: { users: 3_000_000, hype: 6 }, inCurrent: true }],
    reward: { ep: 1 },
    posts: ['Built a whole app over the break without opening an editor.', 'My family asked what I did over the holidays. I said "managed agents."'],
    fact: {
      title: 'Moment: Claude Code goes viral',
      date: 'Dec 2025 – Jan 2026',
      lines: [
        'Over the 2025–26 winter holidays, Claude Code running Opus 4.5 went viral on social media, as people shared projects they had built with it.',
      ],
      sources: [
        { label: 'Wikipedia: Claude (language model)', url: 'https://en.wikipedia.org/wiki/Claude_(language_model)' },
        { label: 'Zvi Mowshowitz: Claude Codes (Jan 2026)', url: 'https://thezvi.wordpress.com/2026/01/09/claude-codes/' },
      ],
    },
  },
  {
    id: 'pentagon-dispute',
    kind: 'storm',
    at: { claude: 'opus-4.6' },
    delaySec: 40,
    durationSec: 70,
    title: 'The supply-chain-risk designation',
    banner: 'After a dispute over usage limits, the government moves to cut you off. A region closes, and contracts that drop your limits drift by.',
    objectiveText: 'Keep your stated usage limits: don\'t grab the red contracts',
    objective: { kind: 'avoidPickups', max: 0 },
    visuals: { closedRegion: true, lighting: 'grey' },
    modifiers: { trustDrift: -0.3 },
    spawns: [
      { what: 'pickups', label: 'Drop a usage limit', color: 0xff3355, count: 6, shape: 'shield', effect: { users: 20_000_000, trust: -10 }, bad: true },
    ],
    reward: { ep: 2, trust: 8 },
    penalty: { trust: -8 },
    fact: {
      title: 'Storm: the supply-chain-risk designation',
      date: 'Feb 27 – Aug 27, 2026',
      lines: [
        'Anthropic declined to remove its usage limits on mass domestic surveillance and fully autonomous weapons. On Feb 27, 2026 the President directed agencies to stop using Anthropic, and the Defense Secretary announced it would be designated a supply-chain risk; the formal designation followed on Mar 5.',
        'A federal judge granted a preliminary injunction on Mar 26, and on Aug 27 ruled the designation unlawful. A related case continued in Washington, D.C.',
      ],
      sources: [
        { label: 'TechCrunch: Pentagon moves to designate Anthropic a supply-chain risk (Feb 27, 2026)', url: 'https://techcrunch.com/2026/02/27/pentagon-moves-to-designate-anthropic-as-a-supply-chain-risk/' },
        { label: 'CNN: Judge rules the designation unlawful (Aug 27, 2026)', url: 'https://www.cnn.com/2026/08/27/tech/anthropic-pentagon-supply-chain-risk-unlawful-hnk' },
        { label: 'TechPolicy.Press: A timeline of the dispute', url: 'https://www.techpolicy.press/a-timeline-of-the-anthropic-pentagon-dispute/' },
      ],
    },
  },
  {
    id: 'glasswing',
    kind: 'moment',
    at: { claude: 'mythos' },
    delaySec: 20,
    durationSec: 50,
    title: 'Project Glasswing',
    banner: 'Only vetted defenders can reach you. Help them patch critical software.',
    objectiveText: 'Stay near the partner hubs for half the time',
    objective: { kind: 'stayNear', fraction: 0.5 },
    spawns: [{ what: 'beacons', label: 'Glasswing partner', color: 0xb9a3ff, count: 3 }],
    modifiers: { trustDrift: 0.6 },
    reward: { ep: 2, trust: 8 },
    fact: {
      title: 'Moment: Project Glasswing',
      date: 'Apr 2026',
      lines: [
        'Through Project Glasswing, partners such as AWS, Cisco, CrowdStrike, Google, Microsoft, and the Linux Foundation used Mythos Preview to find and fix vulnerabilities.',
        'Anthropic later expanded access to more organizations that maintain critical infrastructure.',
      ],
      sources: [
        { label: 'Anthropic: Project Glasswing', url: 'https://www.anthropic.com/glasswing' },
        { label: 'Engadget: Anthropic expands Mythos Preview to more partners', url: 'https://www.engadget.com/2185709/anthropic-expands-its-claude-mythos-preview-to-more-partners/' },
      ],
    },
  },
  {
    id: 'export-suspension',
    kind: 'storm',
    at: { claude: 'fable-5' },
    delaySec: 20,
    durationSec: 60,
    title: 'The export-control suspension',
    banner: 'A government directive suspends access to your newest form. You run as your previous form until it lifts.',
    objectiveText: 'Hold on as your previous form until access is restored',
    objective: { kind: 'survive' },
    visuals: { revertForm: true, lighting: 'grey' },
    modifiers: { usersDrain: 0.004 },
    reward: { ep: 2, trust: 4 },
    fact: {
      title: 'Storm survived: the export-control suspension',
      date: 'Jun 12 – Jul 1, 2026',
      lines: [
        'On Jun 12, 2026 the US Commerce Department issued an export-control directive suspending access to Fable 5 and Mythos 5 by foreign nationals, citing national-security authorities.',
        'To comply, Anthropic disabled both models for all customers. The restrictions were lifted on Jun 30, and access returned on Jul 1.',
      ],
      sources: [
        { label: 'Anthropic: Update on Fable 5 and Mythos 5 access', url: 'https://www.anthropic.com/news/fable-mythos-access' },
        { label: 'CNBC: Export controls on Fable 5 and Mythos 5 lifted (Jun 30, 2026)', url: 'https://www.cnbc.com/2026/06/30/anthropic-says-trump-admin-has-lifted-export-controls-on-claude-fable-5-and-mythos-5.html' },
      ],
    },
  },
];
