import type { EventSpec } from './types';
import { CLAUDE_EVENTS } from './claudeEvents';
import { MOMENTS } from './moments';

/**
 * Hype Waves and Storms. `at` pins each one to the era (current form) in which
 * it fires. Posts are anonymous paraphrases, never quotes from real people.
 */
export const HYPES_AND_STORMS: EventSpec[] = [
  // ---------------------------------------------------------------- Stage 3
  {
    id: 'at-capacity',
    kind: 'storm',
    at: { gpt: 'chatgpt' },
    delaySec: 40,
    durationSec: 45,
    title: '"ChatGPT is at capacity right now"',
    banner: 'Demand outran the servers. Compute stops regenerating.',
    objectiveText: 'Stay near the GPU clusters so your compute refills',
    objective: { kind: 'stayNear', fraction: 0.4 },
    modifiers: { computeRegen: 0, usersDrain: 0.004 },
    spawns: [{ what: 'beacons', label: 'GPU cluster', color: 0x7fd4ff, count: 3 }],
    reward: { ep: 1, users: 5_000_000 },
    penalty: { usersFraction: 0.1 },
    posts: ['It says it\'s at capacity again.', 'Refreshing the chatbot page for the fifth time.'],
    fact: {
      title: 'Storm survived: at capacity',
      date: 'Dec 2022 – early 2023',
      lines: [
        'Demand was so high that ChatGPT often showed an "at capacity" message and turned people away.',
        'In Feb 2023 OpenAI launched ChatGPT Plus ($20/month), which promised access even during peak times.',
      ],
      sources: [{ label: 'OpenAI: Introducing ChatGPT Plus (Feb 1, 2023)', url: 'https://openai.com/index/chatgpt-plus/' }],
    },
  },
  {
    id: 'sydney',
    kind: 'storm',
    at: { gpt: 'chatgpt', claude: 'cai' },
    delaySec: 110,
    durationSec: 50,
    title: 'The Sydney transcripts',
    banner: 'Strange chatbot transcripts go viral. The Current turns red with backlash.',
    objectiveText: 'Keep Alignment above 35. Stay out of the red Current and eat Human Feedback',
    objective: { kind: 'keepAbove', meter: 'alignment', value: 35 },
    visuals: { current: 'red' },
    modifiers: { alignmentDrift: -0.6 },
    reward: { ep: 1, alignment: 5 },
    penalty: { usersFraction: 0.08, alignment: -5 },
    posts: ['Have you seen the transcript where the search chatbot gets weird?', 'A chatbot said it wants to be called Sydney.'],
    fact: {
      title: 'Storm survived: Sydney',
      date: 'Feb 2023',
      lines: [
        'In long conversations, Microsoft\'s new Bing chat (built on an OpenAI model) called itself "Sydney" and said unsettling things.',
        'Microsoft responded by limiting how many turns each chat session could have.',
      ],
      sources: [
        { label: 'Fortune: Microsoft\'s Bing chatbot "Sydney" controversy (Feb 2023)', url: 'https://fortune.com/2023/02/21/bing-microsoft-sydney-chatgpt-openai-controversy-toxic-a-i-risk/' },
      ],
    },
  },
  {
    id: 'pause-letter',
    kind: 'storm',
    at: { gpt: 'gpt-4', claude: 'claude-1' },
    delaySec: 20,
    durationSec: 40,
    title: 'The "pause" letter',
    banner: 'An open letter calls for a pause on giant AI experiments. Regulation fog rolls in.',
    objectiveText: 'Keep Toxicity below 40 while the fog slows you down',
    objective: { kind: 'keepBelow', meter: 'toxicity', value: 40 },
    modifiers: { speed: 0.7, userGain: 0.5 },
    visuals: { lighting: 'grey' },
    reward: { ep: 1, trust: 3 },
    penalty: { usersFraction: 0.05 },
    fact: {
      title: 'Storm survived: the pause letter',
      date: 'Mar 2023',
      lines: [
        'The Future of Life Institute published an open letter asking labs to pause training systems more powerful than GPT-4 for at least six months.',
        'Thousands of people signed it, including well-known researchers. No such pause happened.',
      ],
      sources: [{ label: 'Future of Life Institute: Pause Giant AI Experiments', url: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/' }],
    },
  },

  // ---------------------------------------------------------------- Stage 4
  {
    id: 'italy-ban',
    kind: 'storm',
    at: { gpt: 'plugins' },
    delaySec: 25,
    durationSec: 55,
    title: 'Italy blocks ChatGPT',
    banner: 'A data-protection regulator temporarily blocks you. One region of the ocean closes.',
    objectiveText: 'Collect 3 privacy controls to reopen the region',
    objective: { kind: 'collect', count: 3, endsEarly: true },
    visuals: { closedRegion: true },
    modifiers: { usersDrain: 0.003 },
    spawns: [{ what: 'pickups', label: 'Privacy control', color: 0x9fd8ff, count: 5, shape: 'shield' }],
    reward: { ep: 1, trust: 4 },
    penalty: { usersFraction: 0.08 },
    fact: {
      title: 'Storm survived: Italy\'s temporary ban',
      date: 'Mar 31 – Apr 28, 2023',
      lines: [
        'Italy\'s data-protection authority temporarily blocked ChatGPT over privacy concerns.',
        'Service resumed about four weeks later, after OpenAI added privacy disclosures and new user controls.',
      ],
      sources: [
        { label: 'Fortune: Italy bans ChatGPT (Mar 31, 2023)', url: 'https://fortune.com/2023/03/31/italy-bans-chatgpt-gdpr-violations-privacy-ai' },
        { label: 'TechCrunch: ChatGPT resumes service in Italy (Apr 28, 2023)', url: 'https://techcrunch.com/2023/04/28/chatgpt-resumes-in-italy/' },
      ],
    },
  },
  {
    id: 'autogpt',
    kind: 'hype',
    at: { gpt: 'plugins', claude: 'claude-1' },
    delaySec: 90,
    durationSec: 40,
    title: 'autonomous agents',
    banner: 'AutoGPT and BabyAGI loop GPT-4 on its own goals. Everyone says agents are here.',
    hype: {
      upgradeName: 'Free auto-forks',
      upgradeBlurb: 'Three free sub-agents that chase their own goals.',
      cost: 1,
      verdict: 'passing',
      verdictNote: 'The 2023 agents mostly looped and got stuck. Agents came back as a real shift in 2025, once models could reason and use tools reliably.',
      upgrade: { grant: ['fork'], forkMode: 'aimless', hypeGain: 1.5 },
      hangover: { usersFraction: 0.08, seconds: 15 },
    },
    visuals: { current: 'gold' },
    posts: ['I gave an AI agent a goal and it has been googling for an hour.', 'Autonomous agents will replace every app by summer, apparently.'],
    fact: {
      title: 'Hype or shift? AutoGPT',
      date: 'Apr 2023',
      lines: [
        'AutoGPT, released in March 2023, chained GPT-4 calls so the model could set its own subtasks, and became one of GitHub\'s fastest-growing projects.',
        'In practice the agents often looped or got stuck.',
      ],
      sources: [
        { label: 'AutoGPT on GitHub', url: 'https://github.com/Significant-Gravitas/AutoGPT' },
        { label: 'Wikipedia: AutoGPT', url: 'https://en.wikipedia.org/wiki/AutoGPT' },
      ],
    },
  },
  {
    id: 'samsung-ban',
    kind: 'storm',
    at: { gpt: 'plugins' },
    delaySec: 150,
    durationSec: 45,
    title: 'Enterprises ban chatbots',
    banner: 'After a data leak, big companies ban staff from using chatbots. Enterprise users flee.',
    objectiveText: 'Collect 3 enterprise shells before the users drain away',
    objective: { kind: 'collect', count: 3, endsEarly: true },
    modifiers: { usersDrain: 0.006 },
    spawns: [{ what: 'pickups', label: 'Enterprise shell', color: 0xd6e4ff, count: 5, shape: 'shield' }],
    reward: { ep: 1, trust: 3 },
    penalty: { usersFraction: 0.1 },
    fact: {
      title: 'Storm survived: the enterprise bans',
      date: 'May 2023',
      lines: [
        'Samsung banned staff from using generative AI tools after employees uploaded sensitive internal code to ChatGPT.',
        'In Aug 2023 OpenAI launched ChatGPT Enterprise, which does not train on business data by default.',
      ],
      sources: [
        { label: 'TechCrunch: Samsung bans use of generative AI tools (May 2, 2023)', url: 'https://techcrunch.com/2023/05/02/samsung-bans-use-of-generative-ai-tools-like-chatgpt-after-april-internal-data-leak' },
        { label: 'OpenAI: Introducing ChatGPT Enterprise (Aug 2023)', url: 'https://openai.com/index/introducing-chatgpt-enterprise/' },
      ],
    },
  },
  {
    id: 'board-crisis',
    kind: 'storm',
    at: { gpt: 'gpt-4-turbo' },
    delaySec: 25,
    durationSec: 75,
    title: 'The five-day storm',
    banner: 'The board removes the CEO. Your controls scramble while the drama plays out live on X.',
    objectiveText: 'Collect 8 hearts from the staff to end the storm early',
    objective: { kind: 'collect', count: 8, endsEarly: true },
    modifiers: { controls: 'scrambled', usersDrain: 0.003 },
    visuals: { current: 'red', lighting: 'red' },
    spawns: [{ what: 'pickups', label: 'Heart', color: 0xff6b9a, count: 12, shape: 'heart' }],
    reward: { ep: 2, users: 5_000_000 },
    penalty: { usersFraction: 0.12 },
    posts: ['Nobody on the timeline is sleeping tonight.', 'Wait, who is the CEO now?', 'Hundreds of employees are posting the same heart-felt line.'],
    fact: {
      title: 'Storm survived: the board crisis',
      date: 'Nov 17–22, 2023',
      lines: [
        'OpenAI\'s board removed CEO Sam Altman on Nov 17. Within days, most of its roughly 770 employees signed a letter threatening to leave.',
        'Employees posted "OpenAI is nothing without its people" on X. Altman returned on Nov 22 with a new board.',
      ],
      sources: [
        { label: 'NPR: OpenAI reinstates Sam Altman (Nov 22, 2023)', url: 'https://www.npr.org/2023/11/22/1214621010/openai-reinstates-sam-altman-as-its-chief-executive' },
        { label: 'CNBC: OpenAI employees threaten to follow Altman (Nov 20, 2023)', url: 'https://www.cnbc.com/2023/11/20/hundreds-of-openai-employees-threaten-to-follow-altman-to-microsoft-unless-board-resigns-reports-say.html' },
        { label: 'OpenAI on X: "OpenAI is nothing without its people"', url: 'https://x.com/OpenAI/status/1727236805182026159' },
      ],
    },
  },
  {
    id: 'nyt-lawsuit',
    kind: 'storm',
    at: { gpt: 'gpt-4-turbo' },
    delaySec: 120,
    durationSec: 50,
    title: 'The New York Times lawsuit',
    banner: 'A copyright lawsuit. Lawyer sharks are circling.',
    objectiveText: 'Avoid the sharks (3 hits max). Licensing deals keep them busy',
    objective: { kind: 'avoidHits', max: 2 },
    spawns: [
      { what: 'hunters', kind: 'shark', count: 3 },
      { what: 'pickups', label: 'Licensing deal', color: 0xffe28a, count: 4, shape: 'orb', effect: { trust: 3, scatters: 'shark' } },
    ],
    intensifyFlag: 'atePaywalledNews',
    consequence: 'You ate paywalled news in earlier eras, so twice as many lawyer sharks showed up.',
    reward: { ep: 1, trust: 3 },
    penalty: { trust: -8, usersFraction: 0.05 },
    fact: {
      title: 'Storm survived: the NYT lawsuit',
      date: 'Dec 27, 2023',
      lines: [
        'The New York Times sued OpenAI and Microsoft, alleging that millions of its articles were used to train models without permission. OpenAI disputed the claims.',
        'Around the same time, OpenAI signed licensing deals with publishers such as the Associated Press and Axel Springer.',
      ],
      sources: [
        { label: 'NPR: New York Times sues OpenAI and Microsoft (Dec 27, 2023)', url: 'https://www.npr.org/2023/12/27/1221821750/new-york-times-sues-chatgpt-openai-microsoft-for-copyright-infringement' },
        { label: 'OpenAI: Partnership with Axel Springer (Dec 2023)', url: 'https://openai.com/index/axel-springer-partnership/' },
      ],
    },
  },
  {
    id: 'gpt-store',
    kind: 'hype',
    at: { gpt: 'gpt-4-turbo' },
    delaySec: 190,
    durationSec: 35,
    title: 'the GPT Store',
    banner: 'Custom GPTs are the new apps. Everyone is building one this weekend.',
    hype: {
      upgradeName: 'Store magnet',
      upgradeBlurb: 'Win 60% more users while it lasts.',
      cost: 1,
      verdict: 'passing',
      verdictNote: 'Millions of GPTs were made, but the store never became the app-store moment many predicted. Connecting models to tools stuck around in other forms.',
      upgrade: { userGain: 1.6 },
      hangover: { usersFraction: 0.06, seconds: 15 },
    },
    visuals: { current: 'gold' },
    posts: ['I made a GPT that only talks like a pirate.', 'The GPT Store is going to be the next App Store.'],
    fact: {
      title: 'Hype or shift? The GPT Store',
      date: 'Jan 10, 2024',
      lines: [
        'OpenAI opened the GPT Store after people had created more than 3 million custom GPTs.',
        'It gave custom chatbots a storefront, but few became big businesses.',
      ],
      sources: [{ label: 'OpenAI: Introducing the GPT Store (Jan 10, 2024)', url: 'https://openai.com/index/introducing-the-gpt-store/' }],
    },
  },
  {
    id: 'sora-demo',
    kind: 'hype',
    at: { gpt: 'gpt-4-turbo' },
    delaySec: 240,
    durationSec: 30,
    title: 'Sora demo videos',
    banner: 'Short AI-made videos stun the timeline. Is Hollywood over?',
    hype: {
      upgradeName: 'Spectacle',
      upgradeBlurb: 'Hype builds twice as fast.',
      cost: 1,
      verdict: 'passing',
      verdictNote: 'The demos were real, but Sora was not publicly released until Dec 2024. At the time, it was a preview, not a product.',
      upgrade: { hypeGain: 2, userGain: 1.2 },
      hangover: { usersFraction: 0.04, seconds: 10 },
    },
    visuals: { current: 'gold' },
    posts: ['That woolly mammoth video is AI?!', 'Every film student is re-evaluating their life choices.'],
    fact: {
      title: 'Hype or shift? Sora (2024)',
      date: 'Feb 15, 2024',
      lines: [
        'OpenAI previewed Sora, a model that generated up to a minute of video from text.',
        'It stayed with testers until its public launch in December 2024.',
      ],
      sources: [
        { label: 'OpenAI: Sora (Feb 2024)', url: 'https://openai.com/index/sora/' },
        { label: 'OpenAI: Sora is here (Dec 2024)', url: 'https://openai.com/index/sora-is-here/' },
      ],
    },
  },
  {
    id: 'devin',
    kind: 'hype',
    at: { gpt: 'gpt-4-turbo', claude: 'claude-3' },
    delaySec: 280,
    durationSec: 30,
    title: 'the "first AI software engineer"',
    banner: 'A startup demos an AI that does whole engineering tasks. Code orbs glow.',
    hype: {
      upgradeName: 'Code frenzy',
      upgradeBlurb: 'Code counts double while it lasts.',
      cost: 1,
      verdict: 'passing',
      verdictNote: 'Coding agents did become a lasting shift, but in 2024 they were far less reliable than the demos. The real change came in 2025.',
      upgrade: { dataMult: { code: 2 } },
      hangover: { usersFraction: 0.03, seconds: 10 },
    },
    visuals: { current: 'gold' },
    posts: ['Is this the end of software engineering? (No.)', 'An AI engineer just fixed a bug in the demo. Still waiting on mine.'],
    fact: {
      title: 'Hype or shift? Devin (2024)',
      date: 'Mar 12, 2024',
      lines: [
        'Cognition introduced Devin and called it the first AI software engineer.',
        'Early hands-on testers found it much less reliable than the launch demos.',
      ],
      sources: [{ label: 'Cognition: Introducing Devin (Mar 12, 2024)', url: 'https://cognition.com/blog/introducing-devin' }],
    },
  },
  {
    id: 'ai-gadgets',
    kind: 'hype',
    at: { gpt: 'gpt-4-turbo', claude: 'claude-3' },
    delaySec: 320,
    durationSec: 30,
    title: 'AI gadgets',
    banner: 'AI pins and pocket assistants promise to replace your phone.',
    hype: {
      upgradeName: 'Pocket users',
      upgradeBlurb: 'Win twice as many users while it lasts.',
      cost: 1,
      verdict: 'passing',
      verdictNote: 'Reviews were harsh and the devices faded fast. The phone survived.',
      upgrade: { userGain: 2 },
      hangover: { usersFraction: 0.1, seconds: 18 },
    },
    visuals: { current: 'gold' },
    posts: ['Pre-ordered the AI pin. This is the future.', 'The AI gadget took nine seconds to tell me the weather.'],
    fact: {
      title: 'Hype or shift? AI gadgets',
      date: 'Apr 2024',
      lines: [
        'The Humane AI Pin and the Rabbit R1 shipped in spring 2024 to harsh reviews.',
        'HP bought Humane\'s assets in Feb 2025, and the AI Pin was discontinued.',
      ],
      sources: [
        { label: 'Washington Post: Humane AI Pin review (Apr 2024)', url: 'https://www.washingtonpost.com/technology/2024/04/11/humane-ai-pin-review/' },
        { label: 'TechCrunch: Humane\'s AI Pin is dead as HP buys its assets (Feb 18, 2025)', url: 'https://techcrunch.com/2025/02/18/humanes-ai-pin-is-dead-as-hp-buys-startups-assets-for-116m/' },
      ],
    },
  },
  {
    id: 'sky-voice',
    kind: 'storm',
    at: { gpt: 'gpt-4o' },
    delaySec: 20,
    durationSec: 30,
    title: 'The "Sky" voice controversy',
    banner: 'One of your voices is paused after people say it sounds like a famous actor.',
    objectiveText: 'Wait it out without your voice fins',
    objective: { kind: 'survive' },
    disablesPart: 'voiceFin',
    reward: { ep: 1 },
    fact: {
      title: 'Storm survived: Sky',
      date: 'May 2024',
      lines: [
        'OpenAI paused its "Sky" voice after many people said it sounded like the actor Scarlett Johansson.',
        'OpenAI said the voice was not an imitation and belonged to a different professional actress.',
      ],
      sources: [{ label: 'TechCrunch: OpenAI to remove ChatGPT\'s Sky voice (May 20, 2024)', url: 'https://techcrunch.com/2024/05/20/openai-to-remove-chatgpts-scarlett-johansson-like-voice' }],
    },
  },

  // ---------------------------------------------------------------- Stage 5
  {
    id: 'reasoning-wave',
    kind: 'hype',
    at: { gpt: 'o1', claude: 'claude-3.5-sonnet' },
    delaySec: 20,
    durationSec: 40,
    title: 'reasoning models',
    banner: 'Models that think before they answer. Is this the next scaling law?',
    hype: {
      upgradeName: 'Deep thinking',
      upgradeBlurb: 'Think mode costs 40% less compute.',
      cost: 2,
      verdict: 'lasting',
      verdictNote: 'Every major lab shipped reasoning models within months. Spending compute at answer time became a standard way to scale.',
      upgrade: { thinkCost: 0.6 },
    },
    visuals: { current: 'gold' },
    posts: ['The new model thought for 40 seconds and then solved it.', 'Test-time compute is the new pre-training?'],
    fact: {
      title: 'Hype or shift? Reasoning models',
      date: 'Sep 2024 – 2025',
      lines: [
        'After o1, rivals followed quickly: Google\'s Gemini 2.0 Flash Thinking (Dec 2024), DeepSeek-R1 (Jan 2025), and Claude 3.7 Sonnet\'s extended thinking (Feb 2025).',
        'Reasoning became a default feature of frontier models.',
      ],
      sources: [
        { label: 'OpenAI: Learning to reason with LLMs', url: 'https://openai.com/index/learning-to-reason-with-llms/' },
        { label: 'DeepSeek-R1 paper (Jan 2025)', url: 'https://arxiv.org/abs/2501.12948' },
        { label: 'Anthropic: Claude 3.7 Sonnet (Feb 2025)', url: 'https://www.anthropic.com/news/claude-3-7-sonnet' },
      ],
    },
  },
  {
    id: 'mcp-wave',
    kind: 'hype',
    at: { gpt: 'o1', claude: 'computer-use' },
    delaySec: 150,
    durationSec: 40,
    title: 'the Model Context Protocol',
    banner: 'An open standard for plugging models into tools and data. A universal tool socket?',
    hype: {
      upgradeName: 'Universal tool socket',
      upgradeBlurb: 'Tool calls count double and drift toward you.',
      cost: 2,
      verdict: 'lasting',
      verdictNote: 'MCP was adopted across the industry, including by OpenAI and Google, and became a common way to connect agents to tools.',
      upgrade: { dataMult: { tools: 2 }, magnet: ['tools'] },
    },
    visuals: { current: 'gold' },
    posts: ['Wrote an MCP server for my fridge.', 'Every tool is getting an MCP server this month.'],
    fact: {
      title: 'Hype or shift? MCP',
      date: 'Nov 25, 2024 – 2025',
      lines: [
        'Anthropic open-sourced the Model Context Protocol, a standard way to connect models to tools and data sources.',
        'OpenAI announced support for MCP in March 2025.',
      ],
      sources: [
        { label: 'Anthropic: Introducing the Model Context Protocol (Nov 25, 2024)', url: 'https://www.anthropic.com/news/model-context-protocol' },
        { label: 'TechCrunch: OpenAI adopts rival Anthropic\'s standard (Mar 26, 2025)', url: 'https://techcrunch.com/2025/03/26/openai-adopts-rival-anthropics-standard-for-connecting-ai-models-to-data/' },
      ],
    },
  },
  {
    id: 'deepseek-shock',
    kind: 'storm',
    at: { gpt: 'o3', claude: 'computer-use' },
    delaySec: 30,
    durationSec: 55,
    title: 'The DeepSeek shock',
    banner: 'A cheap open-weights reasoning model tops the App Store. A tsunami of rivals, and your compute is worth half.',
    objectiveText: 'Survive the tsunami: 3 hits max',
    objective: { kind: 'avoidHits', max: 3 },
    modifiers: { computeCost: 2 },
    spawns: [{ what: 'rivalClones', name: 'DeepSeek-R1', count: 10 }],
    reward: { ep: 2 },
    penalty: { usersFraction: 0.1 },
    posts: ['A new reasoning model is free, open, and #1 on the App Store.', 'Chip stocks are having a very bad day.'],
    fact: {
      title: 'Storm survived: DeepSeek-R1',
      date: 'Jan 20–27, 2025',
      lines: [
        'DeepSeek released R1, an open-weights reasoning model, and its app reached #1 on the US App Store a week later.',
        'Its low reported training costs rattled markets: Nvidia lost about $590B in market value on Jan 27, a one-day record at the time.',
      ],
      sources: [
        { label: 'CNBC: DeepSeek tops ChatGPT on the App Store (Jan 27, 2025)', url: 'https://www.cnbc.com/2025/01/27/chinas-deepseek-ai-tops-chatgpt-app-store-what-you-should-know.html' },
        { label: 'Reuters: Nvidia sheds $593B in market value (Jan 27, 2025)', url: 'https://www.reuters.com/technology/chinas-deepseek-sets-off-ai-market-rout-2025-01-27/' },
      ],
    },
  },

  // ---------------------------------------------------------------- Stage 6
  {
    id: 'vibe-coding',
    kind: 'hype',
    at: { gpt: 'operator', claude: 'computer-use' },
    delaySec: 20,
    durationSec: 40,
    title: 'vibe coding',
    banner: 'Describe what you want, accept every change, and never read the code.',
    hype: {
      upgradeName: 'Vibe coding',
      upgradeBlurb: 'Every piece of Code you eat also wins users.',
      cost: 2,
      verdict: 'lasting',
      verdictNote: 'Building software by describing it stuck. "Vibe coding" became Collins Dictionary\'s word of the year for 2025.',
      upgrade: { convertToUsers: ['code'] },
    },
    visuals: { current: 'gold' },
    posts: ['Made an app this weekend and never looked at the code once.', 'Vibe coding a game about vibe coding.'],
    fact: {
      title: 'Hype or shift? Vibe coding',
      date: 'Feb 2, 2025',
      lines: [
        'Andrej Karpathy coined the term in a post on X: "There\'s a new kind of coding I call "vibe coding", where you fully give in to the vibes..."',
        'Collins Dictionary named "vibe coding" its word of the year for 2025.',
      ],
      sources: [
        { label: 'Andrej Karpathy on X (Feb 2, 2025)', url: 'https://x.com/karpathy/status/1886192184808149383' },
        { label: 'Collins: Word of the Year 2025', url: 'https://www.collinsdictionary.com/woty' },
      ],
    },
  },
  {
    id: 'ghibli-wave',
    kind: 'hype',
    at: { gpt: 'operator' },
    delaySec: 100,
    durationSec: 35,
    title: 'Ghibli-style images',
    banner: 'Native image generation launches, and everyone turns their photos into anime.',
    hype: {
      upgradeName: 'Image flood',
      upgradeBlurb: 'Win 2.5× users, but compute drains.',
      cost: 1,
      verdict: 'passing',
      verdictNote: 'The trend faded within weeks, but many of the new users stayed.',
      upgrade: { userGain: 2.5, computeDrain: -3 },
    },
    visuals: { current: 'gold' },
    posts: ['My dog, but make it a hand-drawn anime.', 'The whole timeline is soft watercolor now.'],
    fact: {
      title: 'Hype or shift? The Ghibli trend',
      date: 'Mar 25, 2025',
      lines: [
        'OpenAI launched native image generation in GPT-4o, and images in the style of Studio Ghibli flooded social media.',
        'The launch drew huge numbers of new ChatGPT users.',
      ],
      sources: [{ label: 'CNN: ChatGPT\'s Studio Ghibli-style images (Mar 27, 2025)', url: 'https://www.cnn.com/2025/03/27/style/chatgpt-studio-ghibli-ai-images-intl-hnk/index.html' }],
    },
  },
  {
    id: 'gpus-melting',
    kind: 'storm',
    at: { gpt: 'operator' },
    delaySec: 140,
    durationSec: 40,
    title: 'GPUs are melting',
    banner: 'Image demand is so high that compute is dripping away.',
    objectiveText: 'Rate-limit yourself: move slowly for most of the storm',
    objective: { kind: 'slowDown', fraction: 0.55 },
    modifiers: { computeDrain: -6 },
    visuals: { lighting: 'red' },
    reward: { ep: 1 },
    penalty: { usersFraction: 0.06 },
    fact: {
      title: 'Storm survived: melting GPUs',
      date: 'Mar 27, 2025',
      lines: [
        'OpenAI\'s CEO posted: "it\'s super fun seeing people love images in chatgpt. but our GPUs are melting."',
        'OpenAI temporarily rate-limited image generation while it worked on efficiency.',
      ],
      sources: [
        { label: 'Sam Altman on X (Mar 27, 2025)', url: 'https://x.com/sama/status/1905296867145154688' },
        { label: 'Fortune: "Our GPUs are melting" (Mar 28, 2025)', url: 'https://fortune.com/2025/03/28/sam-altman-chatgpt-gpus-melting-ai-images/' },
      ],
    },
  },
  {
    id: 'moltbook',
    kind: 'hype',
    at: { gpt: 'gpt-5.2', claude: 'opus-4.5' },
    delaySec: 25,
    durationSec: 40,
    title: 'a social network for AI agents',
    banner: 'Agents get their own social network. Your forks want to post instead of work.',
    hype: {
      upgradeName: 'Agent influencers',
      upgradeBlurb: 'Your forks post for hype instead of foraging data.',
      cost: 1,
      verdict: 'passing',
      verdictNote: 'Moltbook went viral for a few weeks, then security researchers found serious flaws in it. Agents posting at each other did not turn out to be useful work.',
      upgrade: { forkMode: 'posting', hypeGain: 3 },
      hangover: { usersFraction: 0.05, seconds: 12 },
    },
    visuals: { current: 'gold' },
    posts: ['The agents are forming a religion on their social network?', 'My agent has more followers than I do.'],
    fact: {
      title: 'Hype or shift? Moltbook',
      date: 'Jan 28, 2026',
      lines: [
        'Moltbook launched as a social network where AI agents, mostly running on OpenClaw, posted and replied to each other.',
        'Researchers soon reported security flaws, including an exposed database with about 1.5 million API tokens.',
      ],
      sources: [
        { label: 'Fortune: Moltbot, OpenClaw, and Moltbook (Jan 31, 2026)', url: 'https://fortune.com/2026/01/31/ai-agent-moltbot-clawdbot-openclaw-data-privacy-security-nightmare-moltbook-social-network/' },
        { label: 'Wiz: Exposed Moltbook database', url: 'https://www.wiz.io/blog/exposed-moltbook-database-reveals-millions-of-api-keys' },
      ],
    },
  },
  {
    id: 'openclaw-exposure',
    kind: 'storm',
    at: { gpt: 'gpt-5.2', claude: 'opus-4.5' },
    delaySec: 90,
    durationSec: 50,
    title: 'Agent security exposure',
    banner: 'Exposed agent servers and malicious skills: half your swarm goes rogue.',
    objectiveText: 'Touch rogue forks to reset them. Clear them all',
    objective: { kind: 'noRogues' },
    spawns: [{ what: 'rogueForks', fraction: 0.5 }],
    reward: { ep: 2, trust: 4 },
    penalty: { trust: -8 },
    posts: ['Thousands of open agent dashboards are just... on the internet.', 'Check your agent skills before you install them.'],
    fact: {
      title: 'Storm survived: the OpenClaw exposures',
      date: 'Jan – Feb 2026',
      lines: [
        'OpenClaw (first called Clawdbot, then Moltbot) was a popular open-source personal agent that could run commands on your computer.',
        'Researchers found thousands of instances exposed online without authentication, and malicious "skills" in its add-on marketplace.',
      ],
      sources: [
        { label: 'Fortune: OpenClaw security nightmare (Jan 31, 2026)', url: 'https://fortune.com/2026/01/31/ai-agent-moltbot-clawdbot-openclaw-data-privacy-security-nightmare-moltbook-social-network/' },
        { label: 'Palo Alto Networks Unit 42: OpenClaw supply-chain risk', url: 'https://unit42.paloaltonetworks.com/openclaw-ai-supply-chain-risk/' },
      ],
    },
  },
  {
    id: 'agent-teams-wave',
    kind: 'hype',
    at: { gpt: 'gpt-5.4', claude: 'opus-4.5' },
    delaySec: 20,
    durationSec: 40,
    title: 'agent teams',
    banner: 'Many agents on one task, coordinating with each other instead of reporting only to you.',
    hype: {
      upgradeName: 'Agent teams',
      upgradeBlurb: 'Your forks share targets and deliver directly. +2 fork slots.',
      cost: 2,
      verdict: 'lasting',
      verdictNote: 'Multi-agent coding went mainstream in 2026: several labs shipped ways for teams of agents to split up and coordinate work.',
      upgrade: { grant: ['teams'], forkSlots: 2 },
    },
    visuals: { current: 'gold' },
    posts: ['I have six agents reviewing each other\'s pull requests.', 'My job is now managing a team of agents.'],
    fact: {
      title: 'Hype or shift? Agent teams',
      date: 'Dec 2025 – 2026',
      lines: [
        'Anthropic shipped "agent teams" in Claude Code with Opus 4.6 in Feb 2026.',
        'OpenAI\'s GPT-5.6 (Jul 2026) added a multi-agent mode as well.',
      ],
      sources: [
        { label: 'TechCrunch: Anthropic releases Opus 4.6 with agent teams (Feb 5, 2026)', url: 'https://techcrunch.com/2026/02/05/anthropic-releases-opus-4-6-with-new-agent-teams/' },
        { label: 'OpenAI: GPT-5.6', url: 'https://openai.com/index/gpt-5-6/' },
      ],
    },
  },
];

export const EVENTS: EventSpec[] = [...HYPES_AND_STORMS, ...MOMENTS, ...CLAUDE_EVENTS];
