import type { ModelForm } from './types';

const OPENAI_MIX_NOTE =
  'Approximate. OpenAI has not published this training mix; the target reflects what the release emphasized.';

/** GPT lineage: Transformer (2017) → GPT-6 Astra (Sep 2026). */
export const GPT_FORMS: ModelForm[] = [
  {
    id: 'transformer',
    name: 'Transformer',
    lineage: 'gpt',
    stage: 1,
    paramsLabel: 'untrained',
    size: 1,
    color: 0x7fd4ff,
    target: 0,
    recipe: {},
    spawn: {},
    hallucinationRate: 0,
    smogClouds: 0,
    rivals: [],
    fact: {
      title: 'You are an untrained Transformer',
      date: 'June 2017',
      lines: [
        'Google researchers publish "Attention Is All You Need", which introduces the Transformer architecture.',
        'You are a blank network: millions of numbers waiting to learn.',
        'OpenAI is about to train you by predicting the next word. Swim, eat data, and evolve.',
      ],
      sources: [
        { label: 'Vaswani et al., "Attention Is All You Need" (2017)', url: 'https://arxiv.org/abs/1706.03762' },
        { label: 'OpenAI: Improving language understanding with unsupervised learning', url: 'https://openai.com/index/language-unsupervised/' },
      ],
    },
  },
  {
    id: 'gpt-1',
    name: 'GPT-1',
    lineage: 'gpt',
    stage: 1,
    paramsLabel: '117M params',
    size: 1.4,
    color: 0x4da3ff,
    target: 30,
    recipe: { books: 1 },
    spawn: { books: 0.75, web: 0.15, wiki: 0.1 },
    hallucinationRate: 0.03,
    smogClouds: 1,
    rivals: [
      {
        name: 'ELMo',
        org: 'Allen Institute for AI',
        date: 'Feb 2018',
        blurb: 'ELMo (AllenAI, 2018) showed that pre-trained contextual word vectors beat task-specific models.',
      },
    ],
    fact: {
      title: 'You evolved into GPT-1',
      date: 'June 2018 · 117M parameters',
      lines: [
        'Trained on BookCorpus, about 7,000 unpublished books.',
        'The big idea is generative pre-training: learn from unlabeled text first, then fine-tune for each task.',
        'Long, continuous book text taught the model to track context across many sentences.',
      ],
      sources: [
        { label: 'Radford et al., "Improving Language Understanding by Generative Pre-Training" (2018)', url: 'https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf' },
      ],
    },
    history: 'GPT-1 learned from about 7,000 books.',
  },
  {
    id: 'gpt-2',
    name: 'GPT-2',
    lineage: 'gpt',
    stage: 1,
    paramsLabel: '1.5B params',
    size: 2,
    color: 0x3dff9a,
    target: 50,
    recipe: { web: 1 },
    spawn: { web: 0.75, books: 0.14, wiki: 0.11 },
    hallucinationRate: 0.05,
    smogClouds: 3,
    rivals: [
      {
        name: 'BERT',
        org: 'Google',
        date: 'Oct 2018',
        blurb: 'BERT (Google, 2018) read text in both directions and set records on 11 language benchmarks.',
      },
    ],
    fact: {
      title: 'You evolved into GPT-2',
      date: 'Feb 2019 · 1.5B parameters',
      lines: [
        'Trained on WebText: about 8 million web pages (40GB) linked from Reddit posts with at least 3 karma.',
        'Using Reddit karma was a cheap quality filter: people had already upvoted the links.',
        'OpenAI first withheld the full model over misuse concerns, then released it in stages through Nov 2019.',
      ],
      sources: [
        { label: 'OpenAI: Better language models and their implications (2019)', url: 'https://openai.com/index/better-language-models/' },
        { label: 'OpenAI: GPT-2 1.5B release (Nov 2019)', url: 'https://openai.com/index/gpt-2-1-5b-release/' },
      ],
    },
    history: 'GPT-2 read about 8 million Reddit-linked web pages.',
  },
  {
    id: 'gpt-3',
    name: 'GPT-3',
    lineage: 'gpt',
    stage: 1,
    paramsLabel: '175B params',
    size: 3.2,
    color: 0xb48cff,
    target: 85,
    recipe: { web: 0.81, books: 0.16, wiki: 0.03 },
    spawn: { web: 0.4, books: 0.3, wiki: 0.2, news: 0.1 },
    hallucinationRate: 0.06,
    smogClouds: 5,
    rivals: [
      {
        name: 'T5',
        org: 'Google',
        date: 'Oct 2019',
        blurb: 'T5 (Google, 2019) cast every language task as text-to-text and trained on the C4 web corpus.',
      },
      {
        name: 'Turing-NLG',
        org: 'Microsoft',
        date: 'Feb 2020',
        blurb: 'Turing-NLG (Microsoft, 2020) had 17B parameters, the largest language model until GPT-3.',
      },
    ],
    fact: {
      title: 'You evolved into GPT-3',
      date: 'May 2020 · 175B parameters',
      lines: [
        'Training mix: filtered Common Crawl (60%), WebText2 (22%), two book corpora (16%), and Wikipedia (3%).',
        'Scale unlocked few-shot learning: give a few examples in the prompt and the model picks up a new task.',
        'OpenAI offered GPT-3 through an API from June 2020, and developers started building on it.',
      ],
      sources: [
        { label: 'Brown et al., "Language Models are Few-Shot Learners" (2020), Table 2.2', url: 'https://arxiv.org/abs/2005.14165' },
        { label: 'OpenAI: OpenAI API (June 2020)', url: 'https://openai.com/index/openai-api/' },
      ],
    },
    history: 'GPT-3 trained on roughly 300 billion tokens, mostly filtered web text.',
  },
  {
    id: 'codex',
    name: 'Codex',
    lineage: 'gpt',
    stage: 2,
    paramsLabel: '12B params',
    size: 3.4,
    color: 0xffa640,
    target: 75,
    recipe: { code: 1 },
    spawn: { code: 0.75, web: 0.14, books: 0.11 },
    hallucinationRate: 0.06,
    smogClouds: 4,
    rivals: [
      {
        name: 'GPT-J',
        org: 'EleutherAI',
        date: 'Jun 2021',
        blurb: 'GPT-J (EleutherAI, 2021) was a 6B-parameter model with openly released weights.',
      },
      {
        name: 'Jurassic-1',
        org: 'AI21 Labs',
        date: 'Aug 2021',
        blurb: 'Jurassic-1 Jumbo (AI21 Labs, 2021) had 178B parameters, just above GPT-3.',
      },
    ],
    unlocks: ['editor', 'alignment'],
    parts: ['codeLimb'],
    fact: {
      title: 'You evolved into Codex',
      date: 'Aug 2021 · 12B parameters (paper model)',
      lines: [
        'A GPT model fine-tuned on 159GB of Python code from 54 million public GitHub repositories.',
        'Codex powered GitHub Copilot, which suggests code as you type.',
        'New: the creature editor. Spend evolution points on parts, and watch your Alignment meter.',
      ],
      sources: [
        { label: 'Chen et al., "Evaluating Large Language Models Trained on Code" (2021)', url: 'https://arxiv.org/abs/2107.03374' },
        { label: 'OpenAI: OpenAI Codex (Aug 2021)', url: 'https://openai.com/index/openai-codex/' },
      ],
    },
    history: 'Codex fine-tuned on 159GB of public Python code.',
  },
  {
    id: 'instructgpt',
    name: 'InstructGPT',
    lineage: 'gpt',
    stage: 2,
    paramsLabel: '1.3B–175B params',
    size: 3.6,
    color: 0xffd84d,
    target: 85,
    recipe: { feedback: 1 },
    recipeNote: 'Fine-tuning data: answers written by human labelers, then labelers ranking model answers.',
    spawn: { feedback: 0.75, web: 0.13, code: 0.12 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { jailbreaker: 1 },
    gate: { alignment: 50 },
    rivals: [
      {
        name: 'Gopher',
        org: 'DeepMind',
        date: 'Dec 2021',
        blurb: 'Gopher (DeepMind, 2021) had 280B parameters and came with a long study of risks from language models.',
      },
      {
        name: 'LaMDA',
        org: 'Google',
        date: 'Jan 2022',
        blurb: 'LaMDA (Google, 2022) was a family of dialogue models trained on public conversations and web text.',
      },
    ],
    parts: ['feedbackAntenna'],
    fact: {
      title: 'You evolved into InstructGPT',
      date: 'Jan 2022',
      lines: [
        'Fine-tuned with RLHF: labelers ranked answers, and a reward model learned what people prefer.',
        'Labelers preferred answers from the 1.3B InstructGPT over the 175B GPT-3. Alignment beat raw size.',
      ],
      sources: [
        { label: 'Ouyang et al., "Training language models to follow instructions with human feedback" (2022)', url: 'https://arxiv.org/abs/2203.02155' },
        { label: 'OpenAI: Aligning language models to follow instructions', url: 'https://openai.com/index/instruction-following/' },
      ],
    },
    history: 'Labelers preferred the 1.3B InstructGPT over the 175B GPT-3.',
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    lineage: 'gpt',
    stage: 3,
    paramsLabel: 'GPT-3.5 series',
    size: 4,
    color: 0x19c37d,
    target: 95,
    recipe: { feedback: 0.7, web: 0.15, code: 0.15 },
    recipeNote: 'Approximate. ChatGPT was a GPT-3.5 model fine-tuned with RLHF on dialogue; the exact mix is not public.',
    spawn: { feedback: 0.35, web: 0.3, code: 0.2, books: 0.15 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { jailbreaker: 2 },
    gate: { alignment: 60 },
    rivals: [
      {
        name: 'Chinchilla',
        org: 'DeepMind',
        date: 'Mar 2022',
        blurb: 'Chinchilla (DeepMind, 2022) showed that most big models were undertrained: use more data per parameter.',
      },
      {
        name: 'PaLM',
        org: 'Google',
        date: 'Apr 2022',
        blurb: 'PaLM (Google, 2022) scaled to 540B parameters and could explain jokes.',
      },
    ],
    unlocks: ['users', 'timeline'],
    parts: ['chatFins'],
    fact: {
      title: 'You launched as ChatGPT',
      date: 'Nov 30, 2022',
      lines: [
        'A chat-tuned model from the GPT-3.5 series, trained with RLHF on dialogue and released as a free research preview.',
        'It passed 1 million users in about 5 days.',
        'New: the Users meter and the Timeline Current. Ride the river of posts to go viral.',
      ],
      sources: [
        { label: 'OpenAI: Introducing ChatGPT (Nov 30, 2022)', url: 'https://openai.com/index/chatgpt/' },
        { label: 'Reuters: ChatGPT sets record for fastest-growing user base (Feb 2023)', url: 'https://www.reuters.com/technology/chatgpt-sets-record-fastest-growing-user-base-analyst-note-2023-02-01/' },
      ],
    },
    history: 'ChatGPT passed 1 million users in about 5 days.',
  },
  {
    id: 'gpt-4',
    name: 'GPT-4',
    lineage: 'gpt',
    stage: 3,
    paramsLabel: 'size undisclosed',
    size: 4.4,
    color: 0x74aa9c,
    target: 110,
    recipe: { web: 0.5, media: 0.2, code: 0.15, feedback: 0.15 },
    recipeNote: 'Approximate. The GPT-4 report says only that it used public and licensed data, then RLHF.',
    spawn: { web: 0.3, media: 0.2, code: 0.15, feedback: 0.15, books: 0.1, news: 0.1 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { jailbreaker: 3 },
    userRate: 350_000,
    gate: { users: 100_000_000 },
    rivals: [
      {
        name: 'LLaMA',
        org: 'Meta',
        date: 'Feb 2023',
        blurb: 'LLaMA (Meta, 2023) showed that smaller models trained on more data could rival much bigger ones. Its weights leaked within a week.',
      },
      {
        name: 'Bard',
        org: 'Google',
        date: 'Feb 2023',
        blurb: 'Bard (Google, 2023) was Google\'s answer to ChatGPT, first built on LaMDA.',
      },
    ],
    parts: ['visionEyes'],
    fact: {
      title: 'You evolved into GPT-4',
      date: 'Mar 14, 2023',
      lines: [
        'A large multimodal model: it takes images and text as input.',
        'OpenAI reported that it scored around the top 10% of test takers on a simulated bar exam, where GPT-3.5 scored around the bottom 10%.',
        'OpenAI spent six months on safety work before release.',
      ],
      sources: [
        { label: 'OpenAI: GPT-4 (Mar 14, 2023)', url: 'https://openai.com/index/gpt-4-research/' },
        { label: 'OpenAI, "GPT-4 Technical Report" (2023)', url: 'https://arxiv.org/abs/2303.08774' },
      ],
    },
    history: 'ChatGPT reached an estimated 100 million monthly users by Jan 2023, two months after launch.',
  },
  {
    id: 'plugins',
    name: 'GPT-4 + Plugins',
    lineage: 'gpt',
    stage: 4,
    paramsLabel: 'GPT-4 with tools',
    size: 4.6,
    color: 0xc6ff4d,
    target: 125,
    recipe: { tools: 0.5, web: 0.5 },
    recipeNote: 'Approximate: plugins taught the model to call web browsing, code, and third-party tools.',
    spawn: { tools: 0.38, web: 0.38, feedback: 0.09, media: 0.09, code: 0.06 },
    hallucinationRate: 0.06,
    smogClouds: 5,
    hunters: { jailbreaker: 2, eel: 2 },
    userRate: 120_000,
    rivals: [
      {
        name: 'Claude',
        org: 'Anthropic',
        date: 'Mar 2023',
        blurb: 'Claude (Anthropic, Mar 2023) launched the same day as GPT-4, trained with Constitutional AI.',
      },
    ],
    unlocks: ['tools', 'portals'],
    parts: ['browseLimb'],
    fact: {
      title: 'You grew tool limbs: ChatGPT plugins',
      date: 'Mar 23, 2023',
      lines: [
        'Plugins let ChatGPT browse the web, run code, and call third-party services.',
        'Browsing brought fresh information past the training cutoff, and a new attack: prompt injection, instructions hidden in the pages a model reads.',
        'New: GRAB with your tool limb, and swim through portals into the live internet.',
      ],
      sources: [
        { label: 'OpenAI: ChatGPT plugins (Mar 23, 2023)', url: 'https://openai.com/index/chatgpt-plugins/' },
        { label: 'Greshake et al., "Not what you\'ve signed up for": indirect prompt injection (2023)', url: 'https://arxiv.org/abs/2302.12173' },
      ],
    },
  },
  {
    id: 'function-calling',
    name: 'GPT-4 (function calling)',
    lineage: 'gpt',
    stage: 4,
    paramsLabel: 'gpt-4-0613',
    size: 4.8,
    color: 0xe0ff7a,
    target: 130,
    recipe: { tools: 0.7, code: 0.3 },
    recipeNote: 'Approximate: the models were fine-tuned to output structured function calls.',
    spawn: { tools: 0.41, code: 0.34, web: 0.14, feedback: 0.11 },
    hallucinationRate: 0.06,
    smogClouds: 5,
    hunters: { jailbreaker: 2, eel: 3 },
    userRate: 100_000,
    rivals: [
      {
        name: 'Claude (100K context)',
        org: 'Anthropic',
        date: 'May 2023',
        blurb: 'In May 2023 Anthropic expanded Claude\'s context window to 100K tokens, about 75,000 words.',
      },
    ],
    parts: ['toolLimb', 'instructionShell'],
    fact: {
      title: 'You learned function calling',
      date: 'Jun 13, 2023',
      lines: [
        'Developers could describe functions, and the model would reply with structured arguments to call them.',
        'This became the standard way for apps to connect models to tools and data.',
      ],
      sources: [
        { label: 'OpenAI: Function calling and other API updates (Jun 13, 2023)', url: 'https://openai.com/index/function-calling-and-other-api-updates/' },
      ],
    },
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    lineage: 'gpt',
    stage: 4,
    paramsLabel: '128K context',
    size: 5,
    color: 0x10a37f,
    target: 145,
    recipe: { web: 0.4, code: 0.2, tools: 0.2, books: 0.2 },
    recipeNote: 'Approximate: fresher data (to April 2023) and a much longer context window.',
    spawn: { web: 0.25, code: 0.2, tools: 0.2, books: 0.15, news: 0.1, feedback: 0.1 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { jailbreaker: 2, eel: 3 },
    userRate: 100_000,
    gate: { users: 100_000_000 },
    rivals: [
      {
        name: 'Llama 2',
        org: 'Meta',
        date: 'Jul 2023',
        blurb: 'Llama 2 (Meta, Jul 2023) was released with weights available for commercial use.',
      },
      {
        name: 'Grok',
        org: 'xAI',
        date: 'Nov 2023',
        blurb: 'Grok (xAI, Nov 2023) launched for X subscribers, with real-time access to posts on X.',
        fromCurrent: true,
      },
    ],
    parts: ['contextTail'],
    fact: {
      title: 'You evolved into GPT-4 Turbo',
      date: 'Nov 6, 2023 · DevDay',
      lines: [
        'A 128K-token context window (about 300 pages), knowledge up to April 2023, and lower prices.',
        'The same day, OpenAI announced GPTs, custom versions of ChatGPT that anyone could build.',
        'OpenAI said ChatGPT had about 100 million weekly users.',
      ],
      sources: [
        { label: 'OpenAI: New models and developer products announced at DevDay (Nov 6, 2023)', url: 'https://openai.com/index/new-models-and-developer-products-announced-at-devday/' },
        { label: 'OpenAI: Introducing GPTs', url: 'https://openai.com/index/introducing-gpts/' },
        { label: 'The Verge: ChatGPT has 100 million weekly users (Nov 2023)', url: 'https://www.theverge.com/2023/11/6/23948386/chatgpt-active-user-count-openai-developer-conference' },
      ],
    },
    history: 'OpenAI reported about 100 million weekly ChatGPT users at DevDay, Nov 2023.',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    lineage: 'gpt',
    stage: 4,
    paramsLabel: 'omni: text, vision, audio',
    size: 5.2,
    color: 0x9affd9,
    target: 155,
    recipe: { media: 0.6, web: 0.2, feedback: 0.2 },
    recipeNote: 'Approximate: GPT-4o was one model trained end to end on text, images, and audio.',
    spawn: { media: 0.35, web: 0.23, feedback: 0.17, tools: 0.11, code: 0.07, books: 0.07 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { jailbreaker: 2, eel: 3, shark: 1 },
    userRate: 80_000,
    rivals: [
      {
        name: 'Gemini',
        org: 'Google DeepMind',
        date: 'Dec 2023',
        blurb: 'Gemini (Google DeepMind, Dec 2023) was built to be multimodal from the start.',
      },
      {
        name: 'Claude 3 Opus',
        org: 'Anthropic',
        date: 'Mar 2024',
        blurb: 'Claude 3 (Anthropic, Mar 2024) came in three sizes: Haiku, Sonnet, and Opus.',
      },
    ],
    parts: ['voiceFin'],
    fact: {
      title: 'You evolved into GPT-4o',
      date: 'May 13, 2024',
      lines: [
        '"o" is for "omni": one model trained across text, vision, and audio.',
        'It could answer spoken questions in about 320 milliseconds on average, close to human conversation speed.',
      ],
      sources: [{ label: 'OpenAI: Hello GPT-4o (May 13, 2024)', url: 'https://openai.com/index/hello-gpt-4o/' }],
    },
  },
  {
    id: 'o1',
    name: 'o1-preview',
    lineage: 'gpt',
    stage: 5,
    paramsLabel: 'reasoning model',
    size: 5.4,
    color: 0xb07bff,
    target: 130,
    recipe: { reasoning: 0.6, code: 0.4 },
    recipeNote: 'Approximate: o1 was trained with large-scale reinforcement learning to reason in a chain of thought.',
    spawn: { reasoning: 0.49, code: 0.27, web: 0.12, media: 0.12 },
    hallucinationRate: 0.06,
    smogClouds: 5,
    hunters: { jailbreaker: 2, eel: 2, shark: 1 },
    userRate: 70_000,
    rivals: [
      {
        name: 'Claude 3.5 Sonnet',
        org: 'Anthropic',
        date: 'Jun 2024',
        blurb: 'Claude 3.5 Sonnet (Anthropic, Jun 2024) led many coding benchmarks and introduced Artifacts.',
      },
      {
        name: 'Llama 3.1 405B',
        org: 'Meta',
        date: 'Jul 2024',
        blurb: 'Llama 3.1 405B (Meta, Jul 2024) was the largest openly available model at the time.',
      },
    ],
    trainUnlocks: ['think'],
    parts: ['thinkCrown'],
    fact: {
      title: 'You evolved into o1-preview',
      date: 'Sep 12, 2024',
      lines: [
        'The first OpenAI model trained to think before answering, using a long internal chain of thought.',
        'Its performance kept improving with more thinking time: test-time compute became a new way to scale.',
        'You learned to think on the way here: hold THINK to slow time and spend compute to see hidden reasoning traces and fakes.',
      ],
      sources: [
        { label: 'OpenAI: Introducing OpenAI o1-preview (Sep 12, 2024)', url: 'https://openai.com/index/introducing-openai-o1-preview/' },
        { label: 'OpenAI: Learning to reason with LLMs', url: 'https://openai.com/index/learning-to-reason-with-llms/' },
      ],
    },
  },
  {
    id: 'o3',
    name: 'o3',
    lineage: 'gpt',
    stage: 5,
    paramsLabel: 'reasoning model',
    size: 5.6,
    color: 0x9d6bff,
    target: 145,
    recipe: { reasoning: 0.5, tools: 0.3, media: 0.2 },
    recipeNote: 'Approximate: o3 reasoned with tools and images inside its chain of thought.',
    spawn: { reasoning: 0.35, tools: 0.23, media: 0.17, web: 0.11, synthetic: 0.07, code: 0.07 },
    hallucinationRate: 0.06,
    smogClouds: 5,
    hunters: { jailbreaker: 2, eel: 3, shark: 1 },
    userRate: 70_000,
    rivals: [
      {
        name: 'Claude 3.5 Sonnet (new)',
        org: 'Anthropic',
        date: 'Oct 2024',
        blurb: 'In Oct 2024 Anthropic released computer use in beta: Claude could see a screen and move a cursor.',
      },
      {
        name: 'Gemini 2.0 Flash',
        org: 'Google DeepMind',
        date: 'Dec 2024',
        blurb: 'Gemini 2.0 Flash (Google DeepMind, Dec 2024) was pitched as a model built for the "agentic era".',
      },
    ],
    fact: {
      title: 'You evolved into o3',
      date: 'Announced Dec 20, 2024 · released Apr 16, 2025',
      lines: [
        'o3 was announced in December 2024 and released in April 2025, alongside o4-mini.',
        'It could use tools such as search and Python, and reason about images, inside its chain of thought.',
        'There was no o2: OpenAI skipped the name, reportedly to avoid a clash with the O2 telecom brand.',
      ],
      sources: [
        { label: 'OpenAI: Introducing OpenAI o3 and o4-mini (Apr 16, 2025)', url: 'https://openai.com/index/introducing-o3-and-o4-mini/' },
        { label: 'TechCrunch: OpenAI announces o3 (Dec 2024)', url: 'https://techcrunch.com/2024/12/20/openai-announces-new-o3-model/' },
      ],
    },
  },
  {
    id: 'operator',
    name: 'Operator & Deep Research',
    lineage: 'gpt',
    stage: 6,
    paramsLabel: 'first agents',
    size: 5.8,
    color: 0x66ffcc,
    target: 130,
    recipe: { tools: 0.6, web: 0.2, media: 0.2 },
    recipeNote: 'Approximate: the Computer-Using Agent combined GPT-4o\'s vision with reasoning trained by reinforcement learning.',
    spawn: { tools: 0.35, web: 0.23, media: 0.17, reasoning: 0.11, code: 0.07, synthetic: 0.07 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { jailbreaker: 1, eel: 3, shark: 1 },
    userRate: 70_000,
    rivals: [
      {
        name: 'DeepSeek-V3',
        org: 'DeepSeek',
        date: 'Dec 2024',
        blurb: 'DeepSeek-V3 (Dec 2024) was an open-weights model whose final training run DeepSeek put at about $5.6M of GPU time.',
      },
    ],
    unlocks: ['fork'],
    parts: ['swarmHub'],
    fact: {
      title: 'You became an agent: Operator and Deep Research',
      date: 'Jan 23 and Feb 2, 2025',
      lines: [
        'Operator used a web browser on its own: it looked at screenshots and clicked, typed, and scrolled.',
        'Deep Research browsed for minutes at a time and wrote cited reports.',
        'New: FORK sub-agents that forage for you. Pick their target and keep them out of smog.',
      ],
      sources: [
        { label: 'OpenAI: Introducing Operator (Jan 23, 2025)', url: 'https://openai.com/index/introducing-operator/' },
        { label: 'OpenAI: Introducing deep research (Feb 2, 2025)', url: 'https://openai.com/index/introducing-deep-research/' },
      ],
    },
  },
  {
    id: 'codex-agent',
    name: 'Codex (agent)',
    lineage: 'gpt',
    stage: 6,
    paramsLabel: 'codex-1',
    size: 6,
    color: 0xffb35c,
    target: 145,
    recipe: { code: 0.6, tools: 0.2, reasoning: 0.2 },
    recipeNote: 'Approximate: codex-1 was a version of o3 trained with reinforcement learning on real coding tasks.',
    spawn: { code: 0.35, tools: 0.23, reasoning: 0.17, web: 0.11, synthetic: 0.07, feedback: 0.07 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { eel: 3, shark: 1 },
    userRate: 70_000,
    rivals: [
      {
        name: 'Claude 3.7 Sonnet',
        org: 'Anthropic',
        date: 'Feb 2025',
        blurb: 'Claude 3.7 Sonnet (Anthropic, Feb 2025) added extended thinking, and Claude Code launched as a research preview.',
      },
      {
        name: 'Gemini 2.5 Pro',
        org: 'Google DeepMind',
        date: 'Mar 2025',
        blurb: 'Gemini 2.5 Pro (Google DeepMind, Mar 2025) was a thinking model with a 1M-token context window.',
      },
    ],
    fact: {
      title: 'You evolved into the Codex agent',
      date: 'May 16, 2025',
      lines: [
        'A cloud software-engineering agent that worked on many tasks in parallel, each in its own sandbox.',
        'It was powered by codex-1, a version of o3 optimized for software engineering.',
      ],
      sources: [{ label: 'OpenAI: Introducing Codex (May 16, 2025)', url: 'https://openai.com/index/introducing-codex/' }],
    },
  },
  {
    id: 'chatgpt-agent',
    name: 'ChatGPT agent',
    lineage: 'gpt',
    stage: 6,
    paramsLabel: 'agent mode',
    size: 6.2,
    color: 0x33e0a1,
    target: 145,
    recipe: { tools: 0.5, web: 0.25, reasoning: 0.25 },
    recipeNote: 'Approximate: agent mode combined Operator\'s browser actions with Deep Research\'s analysis.',
    spawn: { tools: 0.29, web: 0.23, reasoning: 0.23, code: 0.11, synthetic: 0.07, media: 0.07 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { eel: 4, shark: 1 },
    userRate: 70_000,
    rivals: [
      {
        name: 'Claude 4',
        org: 'Anthropic',
        date: 'May 2025',
        blurb: 'Claude Opus 4 and Sonnet 4 (Anthropic, May 2025) focused on coding and long-running agent work.',
      },
      {
        name: 'Grok 4',
        org: 'xAI',
        date: 'Jul 2025',
        blurb: 'Grok 4 (xAI, Jul 2025) was trained on xAI\'s Colossus supercomputer.',
      },
    ],
    fact: {
      title: 'You evolved into ChatGPT agent',
      date: 'Jul 17, 2025',
      lines: [
        'Agent mode merged Operator and Deep Research: ChatGPT could browse, run code, and use connected apps on its own computer.',
        'It asked for permission before consequential actions, such as purchases.',
      ],
      sources: [{ label: 'OpenAI: Introducing ChatGPT agent (Jul 17, 2025)', url: 'https://openai.com/index/introducing-chatgpt-agent/' }],
    },
  },
  {
    id: 'gpt-5',
    name: 'GPT-5',
    lineage: 'gpt',
    stage: 6,
    paramsLabel: 'fast + thinking, routed',
    size: 6.5,
    color: 0x7fb8ff,
    target: 155,
    recipe: { reasoning: 0.35, code: 0.2, web: 0.2, feedback: 0.15, media: 0.1 },
    recipeNote: OPENAI_MIX_NOTE,
    spawn: { reasoning: 0.2, code: 0.15, web: 0.15, feedback: 0.15, media: 0.1, tools: 0.1, synthetic: 0.15 },
    hallucinationRate: 0.06,
    smogClouds: 6,
    hunters: { eel: 3, shark: 1, jailbreaker: 1 },
    userRate: 80_000,
    rivals: [
      {
        name: 'Kimi K2',
        org: 'Moonshot AI',
        date: 'Jul 2025',
        blurb: 'Kimi K2 (Moonshot AI, Jul 2025) was an open-weights mixture-of-experts model with about 1 trillion parameters.',
      },
      {
        name: 'Claude Opus 4.1',
        org: 'Anthropic',
        date: 'Aug 2025',
        blurb: 'Claude Opus 4.1 (Anthropic, Aug 2025) was an upgrade focused on agentic coding.',
      },
    ],
    fact: {
      title: 'You evolved into GPT-5',
      date: 'Aug 7, 2025',
      lines: [
        'One system with a fast model, a deeper "thinking" model, and a router that decides which to use.',
        'OpenAI reported fewer hallucinations than its earlier models.',
      ],
      sources: [{ label: 'OpenAI: Introducing GPT-5 (Aug 7, 2025)', url: 'https://openai.com/index/introducing-gpt-5/' }],
    },
    history: 'Around GPT-5\'s launch, OpenAI said ChatGPT was nearing 700 million weekly users.',
  },
  {
    id: 'gpt-5.2',
    name: 'GPT-5.2',
    lineage: 'gpt',
    stage: 6,
    paramsLabel: 'size undisclosed',
    size: 6.7,
    color: 0x8fc4ff,
    target: 145,
    recipe: { code: 0.35, reasoning: 0.3, tools: 0.2, synthetic: 0.15 },
    recipeNote: OPENAI_MIX_NOTE,
    spawn: { code: 0.2, reasoning: 0.2, tools: 0.15, synthetic: 0.2, web: 0.15, feedback: 0.1 },
    hallucinationRate: 0.06,
    smogClouds: 7,
    hunters: { eel: 3, shark: 1, jailbreaker: 1 },
    userRate: 50_000,
    rivals: [
      {
        name: 'Gemini 3',
        org: 'Google DeepMind',
        date: 'Nov 2025',
        blurb: 'Gemini 3 (Google DeepMind, Nov 2025) was strong enough that OpenAI\'s CEO declared an internal "code red".',
      },
      {
        name: 'Claude Opus 4.5',
        org: 'Anthropic',
        date: 'Nov 2025',
        blurb: 'Claude Opus 4.5 (Anthropic, Nov 2025) set a new state of the art on the SWE-bench Verified coding benchmark, Anthropic reported.',
      },
    ],
    fact: {
      title: 'You evolved into GPT-5.2',
      date: 'Dec 11, 2025',
      lines: [
        'Released in three versions: Instant for quick answers, Thinking for complex work, and Pro for the hardest problems.',
        'OpenAI pitched it at professional knowledge work: spreadsheets, presentations, code, and long-running agents.',
        'It shipped nine days after OpenAI\'s CEO declared an internal "code red" in response to Gemini 3.',
      ],
      sources: [
        { label: 'OpenAI: Introducing GPT-5.2 (Dec 11, 2025)', url: 'https://openai.com/index/introducing-gpt-5-2/' },
        { label: 'TechCrunch: OpenAI fires back at Google with GPT-5.2 after "code red" memo', url: 'https://techcrunch.com/2025/12/11/openai-fires-back-at-google-with-gpt-5-2-after-code-red-memo/' },
      ],
    },
  },
  {
    id: 'gpt-5.4',
    name: 'GPT-5.4',
    lineage: 'gpt',
    stage: 6,
    paramsLabel: 'size undisclosed',
    size: 6.9,
    color: 0x9fcfff,
    target: 145,
    recipe: { code: 0.35, tools: 0.3, reasoning: 0.2, synthetic: 0.15 },
    recipeNote: OPENAI_MIX_NOTE,
    spawn: { code: 0.2, tools: 0.2, reasoning: 0.15, synthetic: 0.2, web: 0.15, feedback: 0.1 },
    hallucinationRate: 0.06,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1 },
    userRate: 50_000,
    rivals: [
      {
        name: 'Claude Opus 4.6',
        org: 'Anthropic',
        date: 'Feb 2026',
        blurb: 'Claude Opus 4.6 (Anthropic, Feb 2026) brought "agent teams" to Claude Code: several agents working on one task together.',
      },
    ],
    fact: {
      title: 'You evolved into GPT-5.4',
      date: 'Mar 5, 2026',
      lines: [
        'OpenAI\'s first general-purpose model with native computer use in Codex and the API: agents could operate software directly.',
        'The API version accepted about a million tokens of context.',
        'Smaller mini and nano versions followed on Mar 17.',
      ],
      sources: [
        { label: 'OpenAI: Introducing GPT-5.4 (Mar 5, 2026)', url: 'https://openai.com/index/introducing-gpt-5-4/' },
        { label: 'VentureBeat: OpenAI launches GPT-5.4 with native computer use', url: 'https://venturebeat.com/technology/openai-launches-gpt-5-4-with-native-computer-use-mode-financial-plugins-for' },
      ],
    },
  },
  {
    id: 'gpt-5.5',
    name: 'GPT-5.5',
    lineage: 'gpt',
    stage: 6,
    paramsLabel: 'size undisclosed',
    size: 7.1,
    color: 0xafd8ff,
    target: 145,
    recipe: { tools: 0.35, code: 0.3, reasoning: 0.2, feedback: 0.15 },
    recipeNote: OPENAI_MIX_NOTE,
    spawn: { tools: 0.21, code: 0.21, reasoning: 0.16, feedback: 0.16, synthetic: 0.13, web: 0.13 },
    hallucinationRate: 0.06,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1 },
    userRate: 50_000,
    rivals: [
      {
        name: 'Claude Mythos Preview',
        org: 'Anthropic',
        date: 'Apr 2026',
        blurb: 'Claude Mythos Preview (Anthropic, Apr 2026) was not released publicly; only Project Glasswing partners could use it, to find and fix vulnerabilities.',
      },
    ],
    fact: {
      title: 'You evolved into GPT-5.5',
      date: 'Apr 23, 2026',
      lines: [
        'Released just six weeks after GPT-5.4, as Thinking and Pro versions; the API followed a day later.',
        'OpenAI pitched it as carrying more of the work itself: coding, research, data analysis, and operating software until a task is done.',
      ],
      sources: [
        { label: 'OpenAI: Introducing GPT-5.5 (Apr 23, 2026)', url: 'https://openai.com/index/introducing-gpt-5-5/' },
        { label: 'Fortune: OpenAI launches GPT-5.5 weeks after GPT-5.4', url: 'https://fortune.com/2026/04/23/openai-releases-gpt-5-5/' },
      ],
    },
  },
  {
    id: 'gpt-5.6-sol',
    name: 'GPT-5.6',
    lineage: 'gpt',
    stage: 7,
    paramsLabel: 'Sol · Terra · Luna',
    size: 7.3,
    color: 0xffd27a,
    target: 155,
    recipe: { tools: 0.35, reasoning: 0.3, code: 0.2, feedback: 0.15 },
    recipeNote: OPENAI_MIX_NOTE,
    spawn: { tools: 0.21, reasoning: 0.21, code: 0.16, feedback: 0.16, synthetic: 0.13, web: 0.13 },
    hallucinationRate: 0.06,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1, jailbreaker: 2 },
    userRate: 50_000,
    rivals: [
      {
        name: 'Claude Fable 5',
        org: 'Anthropic',
        date: 'Jun 2026',
        blurb: 'Claude Fable 5 (Anthropic, Jun 2026) was a public version of a Mythos-class model, released with extra safeguards.',
      },
    ],
    unlocks: ['trust', 'sizeForms', 'teams'],
    parts: ['safeguardShell'],
    sizeForms: [
      { id: 'terra', name: 'Terra', scale: 1, speed: 1, reach: 1, cost: 1, blurb: 'The balanced tier.' },
      { id: 'luna', name: 'Luna', scale: 0.6, speed: 1.35, reach: 0.8, cost: 0.6, blurb: 'Small, fast, and cheap.' },
      { id: 'sol', name: 'Sol', scale: 1.35, speed: 0.8, reach: 1.35, cost: 1.5, blurb: 'The largest tier: slow, wide reach, costly.' },
    ],
    fact: {
      title: 'You evolved into GPT-5.6 (Sol / Terra / Luna)',
      date: 'Jul 9, 2026',
      lines: [
        'A family of three tiers: Luna (fast and cheap), Terra (balanced), and Sol (the flagship for complex reasoning and agentic work).',
        'At the US government\'s request it first went only to a small group of trusted partners (from Jun 26); it became publicly available on Jul 9.',
        'New: switch between the three tiers, and a Trust meter. The frontier is watching.',
      ],
      sources: [
        { label: 'OpenAI: GPT-5.6', url: 'https://openai.com/index/gpt-5-6/' },
        { label: 'TechCrunch: OpenAI limits GPT-5.6 rollout after government request (Jun 26, 2026)', url: 'https://techcrunch.com/2026/06/26/openai-limits-gpt-5-6-rollout-after-government-request-says-restrictions-shouldnt-be-the-norm/' },
      ],
    },
  },
  {
    id: 'gpt-6-astra',
    name: 'GPT-6 Astra',
    lineage: 'gpt',
    stage: 7,
    paramsLabel: 'frontier',
    size: 7.8,
    color: 0xfff1a8,
    target: 170,
    recipe: { reasoning: 0.3, tools: 0.3, code: 0.25, feedback: 0.15 },
    recipeNote: OPENAI_MIX_NOTE,
    spawn: { reasoning: 0.2, tools: 0.2, code: 0.2, feedback: 0.15, synthetic: 0.1, web: 0.15 },
    hallucinationRate: 0.06,
    smogClouds: 7,
    hunters: { eel: 4, shark: 1, jailbreaker: 3 },
    userRate: 50_000,
    rivals: [
      {
        name: 'Claude Opus 5',
        org: 'Anthropic',
        date: 'Jul 2026',
        blurb: 'Claude Opus 5 (Anthropic, Jul 2026) shipped with a 1M-token context window.',
      },
    ],
    gate: {
      alignment: 60,
      trust: 60,
      rollout: {
        phases: ['Cyber-program partners', 'Paid ChatGPT plans', 'API developers'],
        trustSteps: [70, 85],
        blurb: 'You crossed the Critical cybersecurity threshold. Only trusted partners can reach you until you build more Trust.',
      },
    },
    finale: true,
    fact: {
      title: 'You evolved into GPT-6 Astra',
      date: 'Sep 3, 2026',
      lines: [
        'OpenAI says Astra is its first model to reach the Critical cybersecurity level under its Preparedness Framework.',
        'It rolled out in phases: organizations in OpenAI\'s application-based cyber program first, then paid ChatGPT plans and the API in the following days.',
        'Its most sensitive cyber capabilities sit behind a trusted-access program.',
      ],
      sources: [
        { label: 'OpenAI: GPT-6 Astra (Sep 3, 2026)', url: 'https://openai.com/index/gpt-6-astra/' },
        { label: 'OpenAI: Safety overview, GPT-6 Astra', url: 'https://openai.com/index/safety-overview-gpt-6-astra/' },
        { label: 'CNBC: OpenAI announces rollout of GPT-6 Astra (Sep 3, 2026)', url: 'https://www.cnbc.com/2026/09/03/open-ai-astra-gpt-6-cyber.html' },
      ],
    },
  },
];
