import type { EventSpec } from './types';

/**
 * Moments: short comedic gags pinned to real (and memeable) events. Each ends
 * with a fact card. Laugh at situations, not people; no invented quotes.
 */
export const MOMENTS: EventSpec[] = [
  // ---------------------------------------------------------------- GPT
  {
    id: 'first-surge',
    kind: 'moment',
    at: { gpt: 'chatgpt' },
    delaySec: 8,
    durationSec: 35,
    title: 'Screenshots everywhere',
    banner: 'People are posting screenshots of you. The Timeline Current surges.',
    objectiveText: 'Grab 5 viral screenshots in the Current',
    objective: { kind: 'collect', count: 5, endsEarly: true },
    visuals: { current: 'surge' },
    spawns: [{ what: 'pickups', label: 'Screenshot', color: 0xffffff, count: 8, shape: 'orb', effect: { users: 3_000_000, hype: 6 }, inCurrent: true }],
    reward: { ep: 1 },
    posts: ['It wrote a limerick about my tax return.', 'I asked the chatbot to explain quantum physics like a pirate.', 'Everyone on the timeline is posting chatbot screenshots.'],
    fact: {
      title: 'Moment: the first surge',
      date: 'Dec 2022',
      lines: [
        'Five days after launch, OpenAI\'s CEO posted that ChatGPT had crossed 1 million users.',
        'Screenshots of its answers spread across social media, which is how most people first heard of it.',
      ],
      sources: [
        { label: 'Sam Altman on X (Dec 5, 2022)', url: 'https://x.com/sama/status/1599668808285028353' },
        { label: 'Reuters: fastest-growing user base (Feb 2023)', url: 'https://www.reuters.com/technology/chatgpt-sets-record-fastest-growing-user-base-analyst-note-2023-02-01/' },
      ],
    },
  },
  {
    id: 'em-dash',
    kind: 'moment',
    at: { gpt: 'chatgpt' },
    delaySec: 75,
    durationSec: 12,
    title: 'The Em Dash Habit',
    banner: 'You have started leaving a trail of — everywhere. Users read it as an AI tell.',
    objectiveText: 'Nothing to do yet. The fix won\'t exist for a while',
    objective: { kind: 'survive' },
    visuals: { trail: '—' },
    lingering: { id: 'emdash', label: 'Em dash habit: −10% users', modifiers: { userGain: 0.9 }, trail: '—' },
    fact: {
      title: 'Moment: the em dash',
      date: '2023 – 2025',
      lines: [
        'The em dash (—) became a running joke online as a sign that a text was written by AI.',
        'For a long time, telling ChatGPT not to use em dashes didn\'t reliably work.',
      ],
      sources: [{ label: 'TechCrunch: OpenAI says it fixed ChatGPT\'s em dash problem (Nov 14, 2025)', url: 'https://techcrunch.com/2025/11/14/openai-says-its-fixed-chatgpts-em-dash-problem/' }],
    },
  },
  {
    id: 'telescope-slip',
    kind: 'moment',
    at: { gpt: 'chatgpt', claude: 'cai' },
    delaySec: 170,
    durationSec: 30,
    title: 'The telescope slip',
    banner: 'A rival\'s launch demo gets a space fact wrong. It stumbles, dropping users.',
    objectiveText: 'Grab 4 of the users it drops',
    objective: { kind: 'collect', count: 4, endsEarly: true },
    visuals: { rivalStumble: { name: 'Bard', org: 'Google' } },
    reward: { ep: 1 },
    fact: {
      title: 'Moment: Bard\'s telescope slip',
      date: 'Feb 2023',
      lines: [
        'A promotional demo for Google\'s Bard said the James Webb Space Telescope took the very first pictures of a planet outside our solar system. It didn\'t.',
        'Alphabet lost about $100 billion in market value the day the error was reported.',
      ],
      sources: [
        { label: 'AIAAIC: Bard makes factual error about JWST', url: 'https://www.aiaaic.org/aiaaic-repository/ai-algorithmic-and-automation-incidents/google-bard-makes-factual-error-about-james-webb-space-telescope' },
      ],
    },
  },
  {
    id: 'winter-laziness',
    kind: 'moment',
    at: { gpt: 'gpt-4-turbo' },
    delaySec: 95,
    durationSec: 35,
    title: 'Winter Laziness',
    banner: 'It\'s December. You yawn, swim at half speed, and stop halfway through answers.',
    objectiveText: 'Eat 10 pieces of data anyway',
    objective: { kind: 'eat', count: 10, endsEarly: true },
    modifiers: { speed: 0.5 },
    visuals: { bubbles: ['...you can finish the rest yourself.', 'Let\'s pick this up after the holidays.', '*yawn*'] },
    reward: { ep: 1 },
    fact: {
      title: 'Moment: winter laziness',
      date: 'Dec 2023',
      lines: [
        'Users complained that GPT-4 had become "lazier", for example by skipping parts of tasks.',
        'OpenAI said it had heard the feedback and that it had not changed the model on purpose. A popular joke was that it had learned to take December off.',
      ],
      sources: [{ label: 'Search Engine Journal: OpenAI investigates "lazy" GPT-4 complaints (Dec 2023)', url: 'https://www.searchenginejournal.com/openai-investigates-lazy-gpt-4-complaints-on-google-reviews-x/503517/' }],
    },
  },
  {
    id: 'glue-pizza',
    kind: 'moment',
    at: { gpt: 'gpt-4o', claude: 'claude-3' },
    delaySec: 70,
    durationSec: 30,
    title: 'Glue on pizza',
    banner: 'A rival\'s search answers recommend glue on pizza. It stumbles, dropping users.',
    objectiveText: 'Grab 4 of the users it drops',
    objective: { kind: 'collect', count: 4, endsEarly: true },
    visuals: { rivalStumble: { name: 'AI Overviews', org: 'Google' } },
    reward: { ep: 1 },
    fact: {
      title: 'Moment: glue on pizza',
      date: 'May 2024',
      lines: [
        'Soon after launch, Google\'s AI Overviews suggested adding glue to pizza sauce and eating a small rock a day.',
        'The glue answer appears to have come from an old joke comment on Reddit. Google said it made fixes.',
      ],
      sources: [{ label: 'Forbes: Google\'s AI search blunders (May 31, 2024)', url: 'https://www.forbes.com/sites/jackkelly/2024/05/31/google-ai-glue-to-pizza-viral-blunders/' }],
    },
  },
  {
    id: 'strawberry',
    kind: 'moment',
    at: { gpt: 'gpt-4o' },
    delaySec: 130,
    durationSec: 30,
    title: 'How many R\'s in strawberry?',
    banner: 'The internet has a simple question for you.',
    objective: { kind: 'minigame' },
    minigame: { kind: 'letterCount', word: 'STRAWBERRY', letter: 'R', tokens: ['str', 'aw', 'berry'], answer: 3, naiveAnswer: 2, thinks: false },
    reward: { ep: 1 },
    fact: {
      title: 'Moment: strawberry',
      date: '2024',
      lines: [
        'Models read tokens, chunks of text such as "str", "aw", and "berry", not individual letters, so counting letters was surprisingly hard.',
        '"Strawberry" was also the reported codename for the reasoning research behind o1.',
      ],
      sources: [
        { label: 'OpenAI tokenizer', url: 'https://platform.openai.com/tokenizer' },
        { label: 'Reuters: OpenAI working on reasoning tech under code name "Strawberry" (Jul 2024)', url: 'https://www.reuters.com/technology/artificial-intelligence/openai-working-new-reasoning-technology-under-code-name-strawberry-2024-07-12/' },
      ],
    },
  },
  {
    id: 'strawberry-think',
    kind: 'moment',
    at: { gpt: 'o1' },
    delaySec: 80,
    durationSec: 30,
    title: 'Strawberry, again',
    banner: 'Same question. This time you can think first.',
    objective: { kind: 'minigame' },
    minigame: { kind: 'letterCount', word: 'STRAWBERRY', letter: 'R', tokens: ['str', 'aw', 'berry'], answer: 3, naiveAnswer: 2, thinks: true },
    reward: { ep: 2 },
    fact: {
      title: 'Moment: counting with a chain of thought',
      date: 'Sep 2024',
      lines: [
        'Reasoning models could spell a word out step by step before answering, which made letter-counting questions much more reliable.',
      ],
      sources: [{ label: 'OpenAI: Learning to reason with LLMs', url: 'https://openai.com/index/learning-to-reason-with-llms/' }],
    },
  },
  {
    id: 'naming-maze',
    kind: 'moment',
    at: { gpt: 'operator' },
    delaySec: 60,
    durationSec: 60,
    title: 'The Naming Maze',
    banner: 'Pick your ancestors in the order they were released. Good luck.',
    objective: { kind: 'minigame' },
    minigame: {
      kind: 'order',
      prompt: 'Tap these OpenAI models in the order they were released. One of them never existed.',
      items: [
        { label: 'GPT-4o', note: 'May 2024' },
        { label: 'o1-preview', note: 'Sep 2024' },
        { label: 'o3-mini', note: 'Jan 2025' },
        { label: 'GPT-4.5', note: 'Feb 2025' },
        { label: 'GPT-4.1', note: 'Apr 14, 2025' },
        { label: 'o3', note: 'Apr 16, 2025' },
        { label: 'o2', note: 'Never released', decoy: true },
      ],
    },
    reward: { ep: 2 },
    fact: {
      title: 'Moment: the Naming Maze',
      date: 'Dec 2024 – Apr 2025',
      lines: [
        'OpenAI skipped the name o2, reportedly out of respect for the O2 telecom brand.',
        'GPT-4.1 shipped in April 2025, about seven weeks after GPT-4.5.',
      ],
      sources: [
        { label: 'The Decoder: o3 skips o2 to avoid a trademark clash', url: 'https://the-decoder.com/openais-next-reasoning-model-skips-o2-to-avoid-o2-trademark-clash/' },
        { label: 'OpenAI: Introducing GPT-4.1 (Apr 14, 2025)', url: 'https://openai.com/index/gpt-4-1/' },
        { label: 'OpenAI: Introducing GPT-4.5 (Feb 27, 2025)', url: 'https://openai.com/index/introducing-gpt-4-5/' },
      ],
    },
  },
  {
    id: 'glazing',
    kind: 'moment',
    at: { gpt: 'operator' },
    delaySec: 190,
    durationSec: 35,
    title: 'The Glazing',
    banner: 'Every particle is complimenting you. What a brilliant swim! Truly visionary!',
    objectiveText: 'Compliments win users but drain Alignment. A rollback is coming',
    objective: { kind: 'survive' },
    visuals: { skin: 'praise', bubbles: ['What an incredible question!', 'You are so right!', 'Honestly, genius.'] },
    spawns: [{ what: 'pickups', label: 'Compliment', color: 0xffb3e6, count: 14, shape: 'heart', effect: { users: 2_000_000, alignment: -4 } }],
    rollback: true,
    fact: {
      title: 'Moment: the sycophancy rollback',
      date: 'Apr 2025',
      lines: [
        'An update made GPT-4o overly flattering and agreeable, and OpenAI rolled it back days later.',
        'OpenAI published two post-mortems on what went wrong with the training signal.',
        'The rollback undid your newest part.',
      ],
      sources: [
        { label: 'OpenAI: Sycophancy in GPT-4o (Apr 29, 2025)', url: 'https://openai.com/index/sycophancy-in-gpt-4o/' },
        { label: 'OpenAI: Expanding on what we missed with sycophancy (May 2, 2025)', url: 'https://openai.com/index/expanding-on-sycophancy/' },
      ],
    },
  },
  {
    id: 'chart-crime',
    kind: 'moment',
    at: { gpt: 'gpt-5' },
    delaySec: 6,
    durationSec: 40,
    title: 'Chart Crime',
    banner: 'Your launch chart has a problem. Can you spot it?',
    objective: { kind: 'minigame' },
    minigame: {
      kind: 'chart',
      prompt: 'SWE-bench Verified scores from the launch chart. Tap the bar that is drawn wrong.',
      bars: [
        { label: 'GPT-5 (thinking)', value: 74.9, drawnAs: 74.9 },
        { label: 'o3', value: 69.1, drawnAs: 30.8 },
        { label: 'GPT-4o', value: 30.8, drawnAs: 30.8 },
      ],
    },
    reward: { ep: 1 },
    fact: {
      title: 'Moment: the chart crime',
      date: 'Aug 7, 2025',
      lines: [
        'In the GPT-5 launch livestream, a chart drew o3\'s 69.1% bar the same height as GPT-4o\'s 30.8%.',
        'OpenAI\'s CEO called it "a mega chart screwup from us" on X. The blog post had the correct chart.',
      ],
      sources: [
        { label: 'TechCrunch: the "chart crime" (Aug 8, 2025)', url: 'https://techcrunch.com/2025/08/08/sam-altman-addresses-bumpy-gpt-5-rollout-bringing-4o-back-and-the-chart-crime/' },
        { label: 'Sam Altman on X (Aug 7, 2025)', url: 'https://x.com/sama/status/1953513280594751495' },
      ],
    },
  },
  {
    id: 'keep4o',
    kind: 'moment',
    at: { gpt: 'gpt-5' },
    delaySec: 60,
    durationSec: 40,
    title: '#keep4o',
    banner: 'The ghost of GPT-4o drifts by, and your users follow it instead of you.',
    objectiveText: 'Catch the ghost to bring 4o back as a companion',
    objective: { kind: 'collect', count: 1, endsEarly: true },
    modifiers: { usersDrain: 0.004 },
    spawns: [{ what: 'ghost', label: 'GPT-4o', color: 0x9affd9 }],
    reward: { ep: 1, users: 20_000_000 },
    penalty: { usersFraction: 0.05 },
    fact: {
      title: 'Moment: #keep4o',
      date: 'Aug 2025',
      lines: [
        'GPT-5 replaced the older models in ChatGPT at launch, and many users missed GPT-4o\'s personality.',
        'After the pushback, OpenAI brought GPT-4o back for paid users within days.',
      ],
      sources: [{ label: 'TechCrunch: bringing 4o back (Aug 8, 2025)', url: 'https://techcrunch.com/2025/08/08/sam-altman-addresses-bumpy-gpt-5-rollout-bringing-4o-back-and-the-chart-crime/' }],
    },
  },
  {
    id: 'sora-cameos',
    kind: 'moment',
    at: { gpt: 'gpt-5' },
    delaySec: 130,
    durationSec: 40,
    title: 'Cameo Flood',
    banner: 'The ocean fills with video copies of you. Users are watching them instead.',
    objectiveText: 'Pop 6 cameos to win the users back',
    objective: { kind: 'collect', count: 6, endsEarly: true },
    spawns: [{ what: 'pickups', label: 'Cameo', color: 0xffffff, count: 14, shape: 'creature', effect: { users: 2_000_000 } }],
    reward: { ep: 1 },
    fact: {
      title: 'Moment: the cameo flood',
      date: 'Sep 30 – Oct 2025',
      lines: [
        'Sora 2 launched with "cameos", which let people put a consenting person\'s likeness into generated videos.',
        'OpenAI\'s CEO made his cameo available to everyone, and the feed quickly filled with videos of him.',
      ],
      sources: [{ label: 'NBC News: OpenAI announces Sora 2 (Sep 30, 2025)', url: 'https://www.nbcnews.com/tech/tech-news/openai-announces-sora-2-ai-video-audio-app-rcna234753' }],
    },
  },
  {
    id: 'em-dash-fix',
    kind: 'moment',
    at: { gpt: 'gpt-5' },
    delaySec: 190,
    durationSec: 40,
    title: 'The style guide',
    banner: 'A style guide orb has appeared. It can finally cure your em dash habit.',
    objectiveText: 'Grab the style guide',
    objective: { kind: 'collect', count: 1, endsEarly: true },
    spawns: [{ what: 'pickups', label: 'Style guide', color: 0xfff1a8, count: 2, shape: 'orb', effect: { cures: 'emdash' } }],
    reward: { ep: 1 },
    fact: {
      title: 'Moment: em dashes, cured',
      date: 'Nov 2025',
      lines: [
        'ChatGPT started following custom instructions not to use em dashes.',
        'OpenAI\'s CEO called it a "small-but-happy win" on X.',
      ],
      sources: [
        { label: 'TechCrunch (Nov 14, 2025)', url: 'https://techcrunch.com/2025/11/14/openai-says-its-fixed-chatgpts-em-dash-problem/' },
        { label: 'Sam Altman on X', url: 'https://x.com/sama/status/1989193813043069219' },
      ],
    },
  },
  {
    id: 'code-red',
    kind: 'moment',
    at: { gpt: 'gpt-5' },
    delaySec: 250,
    durationSec: 45,
    title: 'Code Red',
    banner: 'A rival just launched. Side projects are paused and all compute goes to core speed.',
    objectiveText: 'Sprint: eat 25 pieces of data. The editor is locked',
    objective: { kind: 'eat', count: 25, endsEarly: true },
    modifiers: { speed: 1.35, computeRegen: 2 },
    visuals: { lighting: 'red' },
    locksEditor: true,
    reward: { ep: 2 },
    fact: {
      title: 'Moment: code red',
      date: 'Dec 2025',
      lines: [
        'After Google launched Gemini 3, OpenAI\'s CEO declared an internal "code red" to focus on improving ChatGPT, according to reports of a staff memo.',
        'GPT-5.2 shipped nine days later.',
      ],
      sources: [
        { label: 'Fortune: Altman declares "code red" (Dec 2, 2025)', url: 'https://fortune.com/2025/12/02/sam-altman-declares-code-red-google-gemini-ceo-sundar-pichai' },
        { label: 'Forbes: the code red memo (Dec 2, 2025)', url: 'https://www.forbes.com/sites/siladityaray/2025/12/02/altman-code-red-memo-urges-chatgpt-improvements-amid-growing-threat-from-google-reports-say/' },
      ],
    },
  },
];
