import type { PartId, PartSlot, PartSpec } from './types';

/** Creature-editor parts. Forms unlock them via `ModelForm.parts`. */
export const PARTS: Record<PartId, PartSpec> = {
  codeLimb: {
    id: 'codeLimb',
    name: 'Code limb',
    slot: 'limb',
    cost: 2,
    color: 0xffa640,
    blurb: 'Pulls Code toward you from further away.',
    mods: { magnet: ['code'] },
  },
  feedbackAntenna: {
    id: 'feedbackAntenna',
    name: 'Feedback antenna',
    slot: 'antenna',
    cost: 2,
    color: 0xffd84d,
    blurb: 'Attracts Human Feedback and slowly raises Alignment.',
    mods: { magnet: ['feedback'], alignmentDrift: 0.4 },
  },
  principleShell: {
    id: 'principleShell',
    name: 'Principle shell',
    slot: 'shell',
    cost: 2,
    color: 0xff9ad5,
    blurb: 'Attracts Constitution principles and halves damage from toxic smog.',
    mods: { magnet: ['constitution'], toxResist: 0.5 },
  },
  chatFins: {
    id: 'chatFins',
    name: 'Chat fins',
    slot: 'fin',
    cost: 2,
    color: 0x19c37d,
    blurb: 'Swim 15% faster and win 20% more users.',
    mods: { speed: 1.15, userGain: 1.2 },
  },
  visionEyes: {
    id: 'visionEyes',
    name: 'Vision eyes',
    slot: 'eyes',
    cost: 2,
    color: 0x5ff2ff,
    blurb: 'See images: attracts Images & Audio and widens your reach by 15%.',
    mods: { magnet: ['media'], reach: 1.15 },
  },
  contextTail: {
    id: 'contextTail',
    name: 'Long-context tail',
    slot: 'tail',
    cost: 3,
    color: 0x7fd4ff,
    blurb: 'A longer context window: reach 30% further.',
    mods: { reach: 1.3 },
  },
  browseLimb: {
    id: 'browseLimb',
    name: 'Browse limb',
    slot: 'limb',
    cost: 2,
    color: 0xc6ff4d,
    blurb: 'Attracts Tool calls and live Web pages. Your GRAB reaches further.',
    mods: { magnet: ['tools', 'web'] },
  },
  toolLimb: {
    id: 'toolLimb',
    name: 'Tool limb',
    slot: 'limb',
    cost: 3,
    color: 0xe0ff7a,
    blurb: 'Structured tool use: Tool calls count double.',
    mods: { magnet: ['tools'], dataMult: { tools: 2 } },
  },
  voiceFin: {
    id: 'voiceFin',
    name: 'Voice fins',
    slot: 'fin',
    cost: 3,
    color: 0x9affd9,
    blurb: 'Talk out loud: win 40% more users.',
    mods: { userGain: 1.4, speed: 1.1 },
  },
  instructionShell: {
    id: 'instructionShell',
    name: 'Instruction-hierarchy shell',
    slot: 'shell',
    cost: 3,
    color: 0xd6e4ff,
    blurb: 'Trusts your instructions over text it reads: blocks prompt injection.',
    mods: { injectionShield: true, toxResist: 0.3 },
  },
  thinkCrown: {
    id: 'thinkCrown',
    name: 'Thinking crown',
    slot: 'crown',
    cost: 3,
    color: 0xb07bff,
    blurb: 'Think mode costs 30% less compute.',
    mods: { thinkCost: 0.7 },
  },
  artifactLimb: {
    id: 'artifactLimb',
    name: 'Artifact limb',
    slot: 'limb',
    cost: 3,
    color: 0xffc27a,
    blurb: 'Builds things people can use: every piece of Code you eat also wins users.',
    mods: { convertToUsers: ['code'], magnet: ['code'] },
  },
  computerLimb: {
    id: 'computerLimb',
    name: 'Computer-use limb',
    slot: 'limb',
    cost: 3,
    color: 0xd4ff99,
    blurb: 'Clicks and types like a person: Tool calls count double and your GRAB is cheaper.',
    mods: { magnet: ['tools'], dataMult: { tools: 2 }, computeCost: 0.85 },
  },
  swarmHub: {
    id: 'swarmHub',
    name: 'Orchestrator hub',
    slot: 'antenna',
    cost: 3,
    color: 0x66ffcc,
    blurb: 'Coordinates sub-agents: +3 fork slots.',
    mods: { forkSlots: 3 },
  },
  safeguardShell: {
    id: 'safeguardShell',
    name: 'Safeguard shell',
    slot: 'shell',
    cost: 3,
    color: 0xfff1a8,
    blurb: 'Classifiers and monitoring: blocks injection and slowly builds Trust.',
    mods: { injectionShield: true, trustDrift: 0.25, toxResist: 0.4 },
  },
};

/** How many parts each slot holds. */
export const SLOT_CAPACITY: Record<PartSlot, number> = {
  limb: 2,
  eyes: 1,
  tail: 1,
  fin: 1,
  crown: 1,
  shell: 1,
  antenna: 1,
};

export const SLOT_LABELS: Record<PartSlot, string> = {
  limb: 'Limbs',
  eyes: 'Eyes',
  tail: 'Tail',
  fin: 'Fins',
  crown: 'Crown',
  shell: 'Shell',
  antenna: 'Antenna',
};
